#!/usr/bin/env python3
"""Turn sampled checks into decided ones, and emit a machine-readable verdict.

The 2026-07-25 completeness audit found ledger rows whose final step was
bounded-length agreement plus random words.  A sample can refute but never
establish, so those rows were set to `EMPIRICAL`.  This script re-establishes
them by reducing each claim to a finite object and traversing it exhaustively,
which is what `COMPUTED` now requires.

Three shapes of claim appear:

  * "this height-1 expression denotes exactly that language" - decided by
    compiling the expression to a DFA and running product reachability against
    the target DFA (`tools/regex_cert.py`).  `A5-GEN145-01`.
  * "this closed-form function of the automaton state equals the group element"
    - decided by a BFS over the product of the two automata, checking the
    identity at every reachable pair.  `A4-FULL-01` step [4], `WATOM-45-01`.
  * "this integer identity holds for every word" - decided by
    `tools.verdict.decide_linear_identity`.  `LAAB-04-01`, `THOMAS-D2-02`.

**2026-07-25, second audit.**  The first version of this file certified
`THOMAS-D2-02` with a state machine on `(parse state, d)` where `d` was defined
to be `-1` exactly when `parse == 1`, and the acceptance test asked whether
`d == -1` when `parse == 1`.  It traversed a finite object completely, carried a
negative control that fired, and sampled nothing.  It also mentioned none of
`|w|_a`, `|w|_b`, `#tok`, `#ab` - the quantities the identity is about - so
every coefficient of the identity could be changed without the program
noticing.  The author had solved the arithmetic by hand and coded the answer;
the program confirmed the author.

Both integer identities are therefore now expressed through
`tools.verdict.decide_linear_identity`, which takes the *meaning* of each
quantity and the coefficients, derives the transition function itself, and
requires every single-coefficient perturbation to be rejected.  There is no
longer a place to write a pre-solved defect.  Every check in this file reports
through `tools.verdict`, so the status it can support is computed rather than
described, and lands in `data/verdicts/completeness_upgrade.json`.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path
from typing import Hashable, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.regex_cert import DFA, compile_regex, equivalence_witness, parse_regex
from tools.verdict import (
    Control,
    Observable,
    Run,
    conjunction,
    decide_linear_identity,
    exhaustive,
)

RUN = Run("scripts/ci/completeness_upgrade.py")

# A check that covers only part of a ledger row names a *step* id, `ROW/step`,
# and never the row itself. Naming the row would let the row inherit a ceiling
# from a component, which is the `A4-STD-01` sub-step loophole: exhaustive atoms
# standing in for an end-to-end claim that was only sampled.


# --------------------------------------------------------------------------
# Generalized-expression constructors (JSON shape of tools/regex_cert.py)
# --------------------------------------------------------------------------

EMPTY = {"op": "empty"}
EPS = {"op": "eps"}


def lit(x: str) -> dict:
    return {"op": "letter", "value": x}


def cat(*args: dict) -> dict:
    return {"op": "concat", "args": list(args)} if args else EPS


def alt(*args: dict) -> dict:
    return {"op": "union", "args": list(args)}


def compl(arg: dict) -> dict:
    return {"op": "compl", "arg": arg}


def star(arg: dict) -> dict:
    return {"op": "star", "arg": arg}


UNIV = compl(EMPTY)  # Sigma*, star height 0


def avoid(x: str) -> dict:
    """Words containing no `x`, i.e. the star-free language usually written x'*.

    Written with complement so that it costs star height ZERO. Writing it as a
    star instead is what pushes these constructions to height 2.
    """
    return compl(cat(UNIV, lit(x), UNIV))


def inter(*args: dict) -> dict:
    return compl(alt(*[compl(a) for a in args]))


def cayley_dfa(alphabet, images, mul, ident, accept=None) -> DFA:
    """Cayley automaton of the group generated by `images`, from the identity."""
    states = {ident}
    frontier = deque([ident])
    transition = {}
    while frontier:
        g = frontier.popleft()
        for x in alphabet:
            h = mul(g, images[x])
            transition[(g, x)] = h
            if h not in states:
                states.add(h)
                frontier.append(h)
    acc = frozenset({ident} if accept is None else accept)
    dfa = DFA(tuple(alphabet), frozenset(states), ident, acc, transition)
    dfa.validate()
    return dfa


def product_universe(left: DFA, right: DFA) -> int:
    """How many product states an equivalence check actually visits.

    Counted rather than estimated.  `tools.verdict.exhaustive` requires the size
    of the object traversed, and a traversal that reports a size it did not
    count is the same kind of unchecked claim the ledger exists to stop.
    """
    start = (left.start, right.start)
    seen = {start}
    frontier = deque([start])
    while frontier:
        pair = frontier.popleft()
        for symbol in left.alphabet:
            nxt = (left.step(pair[0], symbol), right.step(pair[1], symbol))
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return len(seen)


def transition_monoid(machine: DFA) -> list[tuple[Hashable, ...]]:
    """Every transformation of the state set induced by a word.

    Finite because the state set is, and generated from the letters by closure
    under composition -- the standard construction, computed rather than cited
    so that the aperiodicity test below has something to test.
    """
    order = sorted(machine.states, key=repr)
    index = {state: i for i, state in enumerate(order)}
    generators = [
        tuple(index[machine.step(state, letter)] for state in order)
        for letter in machine.alphabet
    ]
    identity = tuple(range(len(order)))
    elements = {identity}
    frontier = deque([identity])
    while frontier:
        element = frontier.popleft()
        for generator in generators:
            product = tuple(generator[i] for i in element)
            if product not in elements:
                elements.add(product)
                frontier.append(product)
    return sorted(elements)


def aperiodic_witness(machine: DFA) -> tuple[Hashable, ...] | None:
    """An element with `m^n != m^(n+1)` for all `n`, or `None` if aperiodic.

    A language is star-free -- equivalently of generalized star-height zero --
    exactly when its syntactic monoid is aperiodic (Schutzenberger 1965).  So a
    witness here is a *lower* bound: it proves the height is at least one, which
    is the half of "exactly one" that an equivalence check cannot give.
    """
    elements = transition_monoid(machine)
    size = len(elements)
    for element in elements:
        power, seen = element, {element}
        stable = False
        for _ in range(size + 1):
            nxt = tuple(element[i] for i in power)
            if nxt == power:
                stable = True
                break
            power = nxt
            seen.add(power)
        if not stable:
            return element
    return None


def decide_equivalence(
    name: str,
    claim_ids,
    *,
    expr: dict,
    alphabet: Sequence[str],
    target: DFA,
    height: int,
    controls: Sequence[tuple[str, str, dict]],
    covers: str = "step",
    rationale: str = "",
) -> "object":
    """Prove `expr` denotes exactly `target`'s language, at star height <= `height`.

    `controls` are deliberately false variants of the *expression*, each with a
    description of what was broken in the claim's own vocabulary.  They are part
    of the check rather than a separate line of output: an equivalence checker
    that accepts a broken expression has not proved anything about the correct
    one, so the two facts belong to the same verdict.
    """
    parsed = parse_regex(expr, alphabet)
    got_height = parsed.star_height()
    compiled = compile_regex(parsed, alphabet)
    witness = equivalence_witness(compiled, target)

    fired = []
    for control_name, mutation, broken in controls:
        broken_witness = equivalence_witness(compile_regex(parse_regex(broken, alphabet), alphabet), target)
        fired.append(Control(control_name, mutation, rejected=broken_witness is not None))

    if got_height > height:
        detail = f"star height {got_height} exceeds the claimed {height}"
        passed = False
    elif witness is not None:
        detail = f"NOT equivalent; shortest distinguishing word {''.join(witness)!r}"
        passed = False
    else:
        detail = (
            f"exact DFA equivalence by product reachability "
            f"(star height {got_height} <= {height}; target {len(target.states)} states)"
        )
        passed = True

    return RUN.add(
        exhaustive(
            name,
            claim_ids,
            passed=passed,
            universe=product_universe(compiled, target),
            detail=detail,
            controls=fired,
            covers=covers,
            rationale=rationale,
        )
    )


# ==========================================================================
# A5-GEN145-01
# ==========================================================================


def a5_target() -> DFA:
    def pmul(p, q):
        return tuple(q[i] for i in p)

    return cayley_dfa(
        ("a", "b"),
        {"a": (1, 2, 0, 3, 4), "b": (3, 1, 2, 4, 0)},  # (123), (145)
        pmul,
        (0, 1, 2, 3, 4),
    )


def a5_expression(first_return: dict | None = None) -> dict:
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")  # a* and b*, both star-free
    C = first_return or alt(cat(a, Bs, a, Bs, a), cat(b, As, b, As, b))
    k1 = star(C)
    k2 = alt(Bs, cat(Bs, a, Bs, a, star(C), a, Bs))
    k3 = alt(Bs, cat(Bs, a, star(C), a, Bs, a, Bs))
    return inter(k1, k2, k3)


def check_a5() -> None:
    print("\n=== A5-GEN145-01: phi(a)=(123), phi(b)=(145), L = phi^-1(e) ===")
    target = a5_target()
    RUN.add(
        exhaustive(
            "A5-GEN145-01 generated group order",
            "A5-GEN145-01",
            passed=len(target.states) == 60,
            universe=len(target.states),
            detail=f"|<(123),(145)>| = {len(target.states)} (expect 60 = |A5|)",
            controls=[Control("order is 60", "the group the Cayley automaton walks", True)],
            load_bearing=False,
        )
    )
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")
    upper = decide_equivalence(
        "A5-GEN145-01 height <= 1",
        "A5-GEN145-01/upper-bound",
        expr=a5_expression(),
        alphabet=("a", "b"),
        target=target,
        height=1,
        controls=[
            (
                "first-return code missing its `b a* b a* b` half",
                "the disjuncts of the first-return code C",
                a5_expression(first_return=cat(a, Bs, a, Bs, a)),
            ),
            (
                "first-return code missing its `a b* a b* a` half",
                "the disjuncts of the first-return code C",
                a5_expression(first_return=cat(b, As, b, As, b)),
            ),
        ],
        covers="claim",
        rationale=(
            "the row's upper-bound half is exactly 'this height-1 expression denotes "
            "phi^-1(e)', and that is what the equivalence decides; the height is "
            "measured on the same expression, so nothing about `<= 1` is left over"
        ),
    )

    # The other half of "exactly one". An equivalence check can only ever give
    # an upper bound; without this the row would be asserting a lower bound that
    # nothing computed. The control is the same test on a language that *is*
    # star-free, so a witness-finder that always finds one would be caught.
    witness = aperiodic_witness(target)
    star_free_control = aperiodic_witness(
        compile_regex(parse_regex(avoid("a"), ("a", "b")), ("a", "b"))
    )
    lower = RUN.add(
        exhaustive(
            "A5-GEN145-01 height >= 1",
            "A5-GEN145-01/lower-bound",
            passed=witness is not None,
            universe=len(transition_monoid(target)),
            detail=(
                "the transition monoid of the 60-state Cayley automaton is not "
                "aperiodic, so the language is not star-free and its height is "
                "at least 1 (Schutzenberger 1965)"
                if witness is not None
                else "no non-aperiodic element found: the lower bound fails"
            ),
            controls=[
                Control(
                    "the star-free language `no a`",
                    "the language whose monoid is tested",
                    rejected=star_free_control is None,
                )
            ],
            covers="claim",
            rationale=(
                "the row's lower-bound half is exactly 'the height is not 0', which by "
                "Schutzenberger is 'the syntactic monoid is not aperiodic'; the monoid "
                "is computed from the same automaton the upper bound uses"
            ),
        )
    )
    RUN.add(
        conjunction(
            "A5-GEN145-01",
            "A5-GEN145-01",
            parts=[upper, lower],
            detail="height <= 1 by exact equivalence and >= 1 by non-aperiodicity",
            rationale=(
                "'exactly one' is the conjunction of an upper and a lower bound, and "
                "both are here. Refute this by naming a third thing the row asserts"
            ),
        )
    )


# ==========================================================================
# A4-FULL-01, step [4]: group element from (P, N[g,p] mod 2)
# ==========================================================================
#
# `scripts/research/a4_full12.py` checks this on 20,000 random words. It is decidable.
#
# Write g = v . t^e with v in V4 and e = eps(g) in Z/3. `direct_all` flips the
# bit N[g,p] at the phase p *before* reading g, and
#
#     group_from_counts(N, P) = ( SUM_{(g,p): N[g,p]=1} tau^p(V(g)) ) . t^P
#
# where the sum is in V4. V4 is elementary abelian, so the sum is order-
# independent and a repeated occurrence cancels exactly as the mod-2 bit does.
# Therefore the whole right-hand side is computed incrementally by a 12-state
# automaton on (phase, running V4 sum), and the claim
#
#     for every w:  S(w) . t^{P(w)} = phi(w)
#
# is decided by a BFS over the 12 x 12 product with the Cayley automaton.


def a4_full_pieces():
    def pmul(p, q):
        return tuple(q[i] for i in p)

    ident = (0, 1, 2, 3)
    t = (1, 2, 0, 3)
    t2 = pmul(t, t)
    v4 = [ident, (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)]
    sigma, eps, vpart = [], {}, {}
    for v in v4:
        for e, te in ((0, ident), (1, t), (2, t2)):
            g = pmul(v, te)
            sigma.append(g)
            eps[g] = e
            vpart[g] = v

    def tau(v):
        return pmul(pmul(t, v), t2)

    def tau_pow(v, k):
        for _ in range(k % 3):
            v = tau(v)
        return v

    return pmul, ident, (ident, t, t2), sigma, eps, vpart, tau_pow


def check_a4_full_step4(shift: int = 0, phase_stride: int = 1) -> tuple[bool, int, str]:
    """Decide `S(w) . t^P = phi(w)` for all w.

    `shift` displaces the tau exponent and `phase_stride` the phase advance;
    either one makes the formula false, so both serve as controls on the claim
    rather than on the search.
    """
    pmul, ident, tpow, sigma, eps, vpart, tau_pow = a4_full_pieces()

    start = ((0, ident), ident)  # ((phase, V4 sum), Cayley state)
    seen = {start}
    frontier = deque([start])
    checked = 0
    while frontier:
        (phase, acc), prod = frontier.popleft()
        # The identity must hold at every reachable state, i.e. for every word.
        if pmul(acc, tpow[phase]) != prod:
            return False, checked, f"violated after a word reaching (phase={phase})"
        checked += 1
        for g in sigma:
            nxt = (
                (
                    (phase + phase_stride * eps[g]) % 3,
                    pmul(acc, tau_pow(vpart[g], phase + shift)),
                ),
                pmul(prod, g),
            )
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return True, checked, f"identity holds at all {checked} reachable product states"


def check_a4_full() -> None:
    print("\n=== A4-FULL-01 step [4]: group element from (P, N[g,p] mod 2) ===")
    ok, universe, detail = check_a4_full_step4()
    controls = [
        Control(
            "tau exponent shifted by 1",
            "the phase at which tau acts in the closed form",
            rejected=not check_a4_full_step4(shift=1)[0],
        ),
        Control(
            "phase advance doubled",
            "the rate at which the phase P advances",
            rejected=not check_a4_full_step4(phase_stride=2)[0],
        ),
    ]
    RUN.add(
        exhaustive(
            "A4-FULL-01 step [4]",
            "A4-FULL-01/step-4",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=controls,
        )
    )


# ==========================================================================
# WATOM-45-01: the 20 staged-count atoms {w : N_r(w) = h mod 5}
# ==========================================================================
#
# `scripts/research/f20_word_problem.py` check [3b] compares each compiled atom with the
# direct staged count on all 8,191 words of length <= 12. The target is a
# regular language with an obvious 20-state automaton — (b-count mod 4, N_r mod
# 5) — so the comparison can simply be decided instead.


def check_watom() -> None:
    print("\n=== WATOM-45-01: the 20 staged-count atoms N_r = h (mod 5) ===")
    from scripts.research.f20_word_problem import W, AL, compile_dfa, dfa, d_min, height
    from scripts.research.f20_word_problem import equivalence_counterexample

    def staged_target(r: int, h: int):
        """(b-count mod 4, N_r mod 5); `a` counts only while the phase is r."""
        index = {(p, c): p * 5 + c for p in range(4) for c in range(5)}
        transitions = [None] * 20
        for (p, c), i in index.items():
            transitions[i] = {
                "a": index[(p, (c + 1) % 5 if p == r else c)],
                "b": index[((p + 1) % 4, c)],
            }
        accept = [index[(p, h)] for p in range(4)]
        return d_min(dfa(transitions, index[(0, 0)], accept))

    assert set(AL) == {"a", "b"}
    bad = []
    for r in range(4):
        for h in range(5):
            witness = equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, h))
            if witness is not None:
                bad.append((r, h, witness))

    # Controls on the claim: each atom is compared against the target for the
    # wrong residue, and against the target for the wrong phase. Both are false
    # statements about the same 20 atoms, so a checker that accepts either has
    # not established the correct one.
    missed_residue = [
        (r, h)
        for r in range(4)
        for h in range(5)
        if equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, (h + 1) % 5))
        is None
    ]
    missed_phase = [
        (r, h)
        for r in range(4)
        for h in range(5)
        if equivalence_counterexample(compile_dfa(W[r][h]), staged_target((r + 1) % 4, h))
        is None
    ]
    equal = RUN.add(
        exhaustive(
            "WATOM-45-01 atoms equal their staged-count DFAs",
            "WATOM-45-01/equality",
            passed=not bad,
            universe=20,
            detail=(
                "all 20 atoms proved equal to their 20-state staged-count DFAs by "
                "complete product reachability"
                if not bad
                else f"{len(bad)} atoms disagree, e.g. {bad[0]}"
            ),
            controls=[
                Control(
                    "residue h -> h+1",
                    "the residue class each atom counts",
                    rejected=not missed_residue,
                ),
                Control(
                    "phase r -> r+1",
                    "the phase at which each atom counts",
                    rejected=not missed_phase,
                ),
            ],
        )
    )

    # The row claims a height, so a height has to be computed. `height` is the
    # syntactic star height of the expression tree; the control is the same
    # measurement on an expression with a star nested inside a star, which must
    # come out above 1 or the measurement is not measuring.
    heights = sorted({height(W[r][h]) for r in range(4) for h in range(5)})
    from scripts.research.f20_word_problem import star as _star, union as _union

    nested = _star(_star(W[0][0]))
    tall = RUN.add(
        exhaustive(
            "WATOM-45-01 atoms have star height 1",
            "WATOM-45-01/height",
            passed=heights == [1],
            universe=20,
            detail=f"syntactic star height of all 20 atoms: {heights}",
            controls=[
                Control(
                    "a star nested inside a star",
                    "the expression whose height is measured",
                    rejected=height(nested) > 1,
                )
            ],
        )
    )
    RUN.add(
        conjunction(
            "WATOM-45-01",
            "WATOM-45-01",
            parts=[equal, tall],
            detail="each atom is the staged-count language, and has star height 1",
            rationale=(
                "the row asserts of the 20 atoms that each *is* the staged-count "
                "language and that each has height <= 1; both are decided, for all 20"
            ),
        )
    )


# ==========================================================================
# LAAB-04-01 and THOMAS-D2-02: arithmetic reductions, decided
# ==========================================================================
#
# Both rows have proved atoms and a *sampled composite*. Each composite is an
# integer identity holding for every word. `decide_linear_identity` takes the
# meaning of each quantity and the coefficients of the identity and derives the
# search itself, so the identity's constants stay perturbable — which is exactly
# what the first version of this file lost.


def check_laab() -> None:
    print("\n=== LAAB-04-01: binom(w,aab) = M1 + 2*M2 (mod 4) ===")
    # Control state: (#a so far mod 8, binom(#a, 2) mod 4). Every quantity that
    # appears in the identity is an observable, never a pre-combined defect.
    RUN.add(
        decide_linear_identity(
            "LAAB-04-01 composite",
            "LAAB-04-01/identity",
            alphabet="ab",
            control_start=(0, 0),
            control_step=lambda s, x: ((s[0] + 1) % 8, (s[1] + s[0]) % 4) if x == "a" else s,
            observables=[
                Observable("binom_aab", lambda s, x, t: s[1] if x == "b" else 0),
                Observable("m1", lambda s, x, t: 1 if (x == "b" and s[0] % 4 in (2, 3)) else 0),
                Observable(
                    "m2", lambda s, x, t: 1 if (x == "b" and s[0] % 8 in (3, 4, 5, 6)) else 0
                ),
            ],
            coefficients={"binom_aab": 1, "m1": -1, "m2": -2},
            modulus=4,
            detail=(
                "M1 = N_2^(4)+N_3^(4) mod 4, M2 = N_3^(8)+N_4^(8)+N_5^(8)+N_6^(8) mod 2"
            ),
        )
    )


def check_thomas() -> None:
    print("\n=== THOMAS-D2-02: the flat token-counting identity ===")
    # Control state: the parse state of the prefix code {b, aa, ab}.
    # 0 = between tokens, 1 = one `a` read and the token is not yet complete.
    RUN.add(
        decide_linear_identity(
            "THOMAS-D2-02 identity",
            "THOMAS-D2-02/identity",
            alphabet="ab",
            control_start=0,
            control_step=lambda p, x: 1 if (p == 0 and x == "a") else 0,
            observables=[
                Observable("n_ab", lambda p, x, q: 1 if (p == 1 and x == "b") else 0),
                Observable("len_a", lambda p, x, q: 1 if x == "a" else 0),
                Observable("len_b", lambda p, x, q: 1 if x == "b" else 0),
                Observable("n_tok", lambda p, x, q: 0 if (p == 0 and x == "a") else 1),
                Observable("tail", lambda p, x, q: 0, terminal=lambda p: 1 if p == 1 else 0),
            ],
            coefficients={"n_ab": 1, "len_a": -1, "len_b": -2, "n_tok": 2, "tail": 1},
            detail=(
                "#ab = |w|_a + 2*|w|_b - 2*#tok - [tail=a] "
                "over the prefix code {b, aa, ab}"
            ),
        )
    )


def main() -> int:
    print("Completeness upgrades for rows demoted by the 2026-07-25 audit.")
    check_a5()
    check_a4_full()
    check_watom()
    check_laab()
    check_thomas()
    return RUN.finish()


if __name__ == "__main__":
    raise SystemExit(main())
