#!/usr/bin/env python3
"""Turn sampled checks into decided ones, and emit a machine-readable verdict.

The 2026-07-25 completeness audit found ledger rows whose final step was
bounded-length agreement plus random words.  A sample can refute but never
establish, so those rows were set to `EMPIRICAL`.  This script repairs the
finite proof obligations by reducing each such obligation to a finite object
and traversing it exhaustively, which is what `COMPUTED` now requires.

Three shapes of claim appear:

  * "this height-1 expression denotes exactly that language" - decided by
    compiling the expression to a DFA and running product reachability against
    the target DFA (`tools/regex_cert.py`).  `A5-GEN145-01`.
  * "this closed-form function of the automaton state equals the group element"
    - decided by a BFS over the product of the two automata, checking the
    identity at every reachable pair.  `A4-FULL-01` step [4], `WATOM-45-01`.
  * "this integer identity holds for every word" - decided by
    `tools.verdict.decide_linear_identity`.  `LAAB-04-01`, `THOMAS-D2-02`.

**2026-07-25, second audit.**  The first version of this file certified
`THOMAS-D2-02` with a state machine on `(parse state, d)` where `d` was defined
to be `-1` exactly when `parse == 1`, and the acceptance test asked whether
`d == -1` when `parse == 1`.  It traversed a finite object completely, carried a
negative control that fired, and sampled nothing.  It also mentioned none of
`|w|_a`, `|w|_b`, `#tok`, `#ab` - the quantities the identity is about - so
every coefficient of the identity could be changed without the program
noticing.  The author had solved the arithmetic by hand and coded the answer;
the program confirmed the author.

Both integer identities are therefore now expressed through
`tools.verdict.decide_linear_identity`, which takes the *meaning* of each
quantity and the coefficients, derives the transition function itself, and
requires every single-coefficient perturbation to be rejected.  There is no
longer a place to write a pre-solved defect.  Every check in this file reports
through `tools.verdict`, so the status it can support is computed rather than
described, and lands in `data/verdicts/completeness_upgrade.json`.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path
from typing import Hashable, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.regex_cert import (
    DFA,
    _concat as dfa_concat,
    _product as dfa_product,
    _star as dfa_star,
    compile_regex,
    equivalence_witness,
    parse_regex,
)
from tools.verdict import (
    Control,
    Observable,
    Run,
    conjunction,
    decide_linear_identity,
    exhaustive,
)

RUN = Run("scripts/ci/completeness_upgrade.py")

# A check that covers only part of a ledger row names a *step* id, `ROW/step`,
# and never the row itself. Naming the row would let the row inherit a ceiling
# from a component, which is the `A4-STD-01` sub-step loophole: exhaustive atoms
# standing in for an end-to-end claim that was only sampled.


# --------------------------------------------------------------------------
# Generalized-expression constructors (JSON shape of tools/regex_cert.py)
# --------------------------------------------------------------------------

EMPTY = {"op": "empty"}
EPS = {"op": "eps"}


def lit(x: str) -> dict:
    return {"op": "letter", "value": x}


def cat(*args: dict) -> dict:
    return {"op": "concat", "args": list(args)} if args else EPS


def alt(*args: dict) -> dict:
    return {"op": "union", "args": list(args)}


def compl(arg: dict) -> dict:
    return {"op": "compl", "arg": arg}


def star(arg: dict) -> dict:
    return {"op": "star", "arg": arg}


UNIV = compl(EMPTY)  # Sigma*, star height 0


def avoid(x: str) -> dict:
    """Words containing no `x`, i.e. the star-free language usually written x'*.

    Written with complement so that it costs star height ZERO. Writing it as a
    star instead is what pushes these constructions to height 2.
    """
    return compl(cat(UNIV, lit(x), UNIV))


def inter(*args: dict) -> dict:
    return compl(alt(*[compl(a) for a in args]))


def cayley_dfa(alphabet, images, mul, ident, accept=None) -> DFA:
    """Cayley automaton of the group generated by `images`, from the identity."""
    states = {ident}
    frontier = deque([ident])
    transition = {}
    while frontier:
        g = frontier.popleft()
        for x in alphabet:
            h = mul(g, images[x])
            transition[(g, x)] = h
            if h not in states:
                states.add(h)
                frontier.append(h)
    acc = frozenset({ident} if accept is None else accept)
    dfa = DFA(tuple(alphabet), frozenset(states), ident, acc, transition)
    dfa.validate()
    return dfa


def product_universe(left: DFA, right: DFA) -> int:
    """How many product states an equivalence check actually visits.

    Counted rather than estimated.  `tools.verdict.exhaustive` requires the size
    of the object traversed, and a traversal that reports a size it did not
    count is the same kind of unchecked claim the ledger exists to stop.
    """
    start = (left.start, right.start)
    seen = {start}
    frontier = deque([start])
    while frontier:
        pair = frontier.popleft()
        for symbol in left.alphabet:
            nxt = (left.step(pair[0], symbol), right.step(pair[1], symbol))
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return len(seen)


def transition_monoid(machine: DFA) -> list[tuple[Hashable, ...]]:
    """Every transformation of the state set induced by a word.

    Finite because the state set is, and generated from the letters by closure
    under composition -- the standard construction, computed rather than cited
    so that the aperiodicity test below has something to test.
    """
    order = sorted(machine.states, key=repr)
    index = {state: i for i, state in enumerate(order)}
    generators = [
        tuple(index[machine.step(state, letter)] for state in order)
        for letter in machine.alphabet
    ]
    identity = tuple(range(len(order)))
    elements = {identity}
    frontier = deque([identity])
    while frontier:
        element = frontier.popleft()
        for generator in generators:
            product = tuple(generator[i] for i in element)
            if product not in elements:
                elements.add(product)
                frontier.append(product)
    return sorted(elements)


def aperiodic_witness(machine: DFA) -> tuple[Hashable, ...] | None:
    """An element with `m^n != m^(n+1)` for all `n`, or `None` if aperiodic.

    A language is star-free -- equivalently of generalized star-height zero --
    exactly when its syntactic monoid is aperiodic (Schutzenberger 1965).  So a
    witness here is a *lower* bound: it proves the height is at least one, which
    is the half of "exactly one" that an equivalence check cannot give.
    """
    elements = transition_monoid(machine)
    size = len(elements)
    for element in elements:
        power, seen = element, {element}
        stable = False
        for _ in range(size + 1):
            nxt = tuple(element[i] for i in power)
            if nxt == power:
                stable = True
                break
            power = nxt
            seen.add(power)
        if not stable:
            return element
    return None


def decide_equivalence(
    name: str,
    claim_ids,
    *,
    expr: dict,
    alphabet: Sequence[str],
    target: DFA,
    height: int,
    controls: Sequence[tuple[str, str, dict]],
    covers: str = "step",
    rationale: str = "",
) -> "object":
    """Prove `expr` denotes exactly `target`'s language, at star height <= `height`.

    `controls` are deliberately false variants of the *expression*, each with a
    description of what was broken in the claim's own vocabulary.  They are part
    of the check rather than a separate line of output: an equivalence checker
    that accepts a broken expression has not proved anything about the correct
    one, so the two facts belong to the same verdict.
    """
    parsed = parse_regex(expr, alphabet)
    got_height = parsed.star_height()
    compiled = compile_regex(parsed, alphabet)
    witness = equivalence_witness(compiled, target)

    fired = []
    for control_name, mutation, broken in controls:
        broken_witness = equivalence_witness(compile_regex(parse_regex(broken, alphabet), alphabet), target)
        fired.append(Control(control_name, mutation, rejected=broken_witness is not None))

    if got_height > height:
        detail = f"star height {got_height} exceeds the claimed {height}"
        passed = False
    elif witness is not None:
        detail = f"NOT equivalent; shortest distinguishing word {''.join(witness)!r}"
        passed = False
    else:
        detail = (
            f"exact DFA equivalence by product reachability "
            f"(star height {got_height} <= {height}; target {len(target.states)} states)"
        )
        passed = True

    return RUN.add(
        exhaustive(
            name,
            claim_ids,
            passed=passed,
            universe=product_universe(compiled, target),
            detail=detail,
            controls=fired,
            covers=covers,
            rationale=rationale,
        )
    )


# ==========================================================================
# A5-GEN145-01
# ==========================================================================


def a5_target() -> DFA:
    def pmul(p, q):
        return tuple(q[i] for i in p)

    return cayley_dfa(
        ("a", "b"),
        {"a": (1, 2, 0, 3, 4), "b": (3, 1, 2, 4, 0)},  # (123), (145)
        pmul,
        (0, 1, 2, 3, 4),
    )


def a5_expression(first_return: dict | None = None) -> dict:
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")  # a* and b*, both star-free
    C = first_return or alt(cat(a, Bs, a, Bs, a), cat(b, As, b, As, b))
    k1 = star(C)
    k2 = alt(Bs, cat(Bs, a, Bs, a, star(C), a, Bs))
    k3 = alt(Bs, cat(Bs, a, star(C), a, Bs, a, Bs))
    return inter(k1, k2, k3)


def check_a5() -> None:
    print("\n=== A5-GEN145-01: phi(a)=(123), phi(b)=(145), L = phi^-1(e) ===")
    target = a5_target()
    alphabet_check = RUN.add(
        exhaustive(
            "A5-GEN145-01 generated group order",
            "A5-GEN145-01",
            passed=len(target.states) == 60,
            universe=len(target.states),
            detail=f"|<(123),(145)>| = {len(target.states)} (expect 60 = |A5|)",
            controls=[Control("order is 60", "the group the Cayley automaton walks", True)],
            load_bearing=False,
        )
    )
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")
    upper = decide_equivalence(
        "A5-GEN145-01 height <= 1",
        "A5-GEN145-01/upper-bound",
        expr=a5_expression(),
        alphabet=("a", "b"),
        target=target,
        height=1,
        controls=[
            (
                "first-return code missing its `b a* b a* b` half",
                "the disjuncts of the first-return code C",
                a5_expression(first_return=cat(a, Bs, a, Bs, a)),
            ),
            (
                "first-return code missing its `a b* a b* a` half",
                "the disjuncts of the first-return code C",
                a5_expression(first_return=cat(b, As, b, As, b)),
            ),
        ],
        covers="claim",
        rationale=(
            "the row's upper-bound half is exactly 'this height-1 expression denotes "
            "phi^-1(e)', and that is what the equivalence decides; the height is "
            "measured on the same expression, so nothing about `<= 1` is left over"
        ),
    )

    # The other half of "exactly one". An equivalence check can only ever give
    # an upper bound; without this the row would be asserting a lower bound that
    # nothing computed. The control is the same test on a language that *is*
    # star-free, so a witness-finder that always finds one would be caught.
    witness = aperiodic_witness(target)
    star_free_control = aperiodic_witness(
        compile_regex(parse_regex(avoid("a"), ("a", "b")), ("a", "b"))
    )
    lower = RUN.add(
        exhaustive(
            "A5-GEN145-01 height >= 1",
            "A5-GEN145-01/lower-bound",
            passed=witness is not None,
            universe=len(transition_monoid(target)),
            detail=(
                "the transition monoid of the 60-state Cayley automaton is not "
                "aperiodic, so the language is not star-free and its height is "
                "at least 1 (Schutzenberger 1965)"
                if witness is not None
                else "no non-aperiodic element found: the lower bound fails"
            ),
            controls=[
                Control(
                    "the star-free language `no a`",
                    "the language whose monoid is tested",
                    rejected=star_free_control is None,
                )
            ],
            covers="claim",
            rationale=(
                "the row's lower-bound half is exactly 'the height is not 0', which by "
                "Schutzenberger is 'the syntactic monoid is not aperiodic'; the monoid "
                "is computed from the same automaton the upper bound uses"
            ),
        )
    )
    token_check = RUN.add(
        conjunction(
            "A5-GEN145-01",
            "A5-GEN145-01",
            parts=[upper, lower],
            detail="height <= 1 by exact equivalence and >= 1 by non-aperiodicity",
            rationale=(
                "'exactly one' is the conjunction of an upper and a lower bound, and "
                "both are here. Refute this by naming a third thing the row asserts"
            ),
        )
    )


# ==========================================================================
# A4-FULL-01, step [4]: group element from (P, N[g,p] mod 2)
# ==========================================================================
#
# `scripts/research/a4_full12.py` checks this on 20,000 random words. It is decidable.
#
# Write g = v . t^e with v in V4 and e = eps(g) in Z/3. `direct_all` flips the
# bit N[g,p] at the phase p *before* reading g, and
#
#     group_from_counts(N, P) = ( SUM_{(g,p): N[g,p]=1} tau^p(V(g)) ) . t^P
#
# where the sum is in V4. V4 is elementary abelian, so the sum is order-
# independent and a repeated occurrence cancels exactly as the mod-2 bit does.
# Therefore the whole right-hand side is computed incrementally by a 12-state
# automaton on (phase, running V4 sum), and the claim
#
#     for every w:  S(w) . t^{P(w)} = phi(w)
#
# is decided by a BFS over the 12 x 12 product with the Cayley automaton.


def a4_full_pieces():
    def pmul(p, q):
        return tuple(q[i] for i in p)

    ident = (0, 1, 2, 3)
    t = (1, 2, 0, 3)
    t2 = pmul(t, t)
    v4 = [ident, (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)]
    sigma, eps, vpart = [], {}, {}
    for v in v4:
        for e, te in ((0, ident), (1, t), (2, t2)):
            g = pmul(v, te)
            sigma.append(g)
            eps[g] = e
            vpart[g] = v

    def tau(v):
        return pmul(pmul(t, v), t2)

    def tau_pow(v, k):
        for _ in range(k % 3):
            v = tau(v)
        return v

    return pmul, ident, (ident, t, t2), sigma, eps, vpart, tau_pow


def check_a4_full_feature_equations(
    pattern_target_shift: int = 0,
    claimed_arrival_shift: int = 0,
    nonmover_exception_shift: int = 0,
) -> tuple[bool, int, str]:
    """Decide the cut-feature/event equations used by the A4 reconstruction.

    For each mover ``g`` and arrival phase ``q``, this traverses the complete
    product of the eleven actual ``CutPat(q, ('2', h, g))`` automata
    (``h != g``) with the direct event counters.  It checks

        XOR_h F(q, hg) = Z_q + XOR_h N'[hg, q]          over F2

    at every reachable state.  The pattern buffers are carried explicitly, so
    the no-boundary-span property is checked rather than assumed.

    ``pattern_target_shift`` changes the terminal letter in every pattern while
    leaving the claimed event counters unchanged.  A nonzero value is a
    deliberately false control.
    """
    _, _, _, sigma, eps, _, _ = a4_full_pieces()
    index = {letter: i for i, letter in enumerate(sigma)}
    epsilon = [eps[letter] for letter in sigma]
    movers = [i for i, value in enumerate(epsilon) if value != 0]
    nonmovers = [i for i, value in enumerate(epsilon) if value == 0]
    total = 0

    # A nonmover h is recovered from the one-letter exception pattern:
    # F(q, h) = Z_q + N[h,q].
    for h in nonmovers:
        for q in range(3):
            start = (0, -1, 0, 0, 0)
            seen = {start}
            frontier = deque([start])
            while frontier:
                phase, buffer, feature, all_cut, count = frontier.popleft()
                total += 1
                if feature != (all_cut ^ count):
                    return (
                        False,
                        total,
                        f"nonmover feature equation failed for letter {h}, phase {q}",
                    )
                for letter in range(len(sigma)):
                    next_phase = (phase + epsilon[letter]) % 3
                    next_feature = feature
                    next_buffer = letter
                    if next_phase == q:
                        if letter != (h + nonmover_exception_shift) % len(sigma):
                            next_feature ^= 1
                            next_buffer = -1
                    next_all_cut = all_cut ^ (next_phase == q)
                    next_count = count ^ (letter == h and next_phase == q)
                    nxt = (
                        next_phase,
                        next_buffer,
                        int(next_feature),
                        int(next_all_cut),
                        int(next_count),
                    )
                    if nxt not in seen:
                        seen.add(nxt)
                        frontier.append(nxt)

    for g in movers:
        target = (g + pattern_target_shift) % len(sigma)
        openers = tuple(h for h in range(len(sigma)) if h != g)
        for q in range(3):
            # phase, preceding input letter, one buffer per actual CutPat,
            # XOR of their parity outputs, all-cut parity, direct pair parity
            start = (0, -1, (-1,) * len(openers), 0, 0, 0)
            seen = {start}
            frontier = deque([start])
            while frontier:
                phase, previous, buffers, feature, all_cut, pairs = frontier.popleft()
                total += 1
                if feature != (all_cut ^ pairs):
                    return (
                        False,
                        total,
                        f"feature equation failed for mover {g}, phase {q}",
                    )

                for letter in range(len(sigma)):
                    next_phase = (phase + epsilon[letter]) % 3
                    next_feature = feature
                    next_buffers = []
                    for opener, buffer in zip(openers, buffers):
                        if next_phase == q:
                            matched = letter == target and buffer == opener
                            if matched:
                                next_buffers.append(letter)
                            else:
                                next_buffers.append(-1)
                                next_feature ^= 1
                        else:
                            next_buffers.append(letter)

                    next_all_cut = all_cut ^ (next_phase == q)
                    is_claimed_pair = (
                        previous != -1
                        and previous != g
                        and letter == g
                        and next_phase == (q + claimed_arrival_shift) % 3
                    )
                    next_pairs = pairs ^ is_claimed_pair
                    nxt = (
                        next_phase,
                        letter,
                        tuple(next_buffers),
                        int(next_feature),
                        int(next_all_cut),
                        int(next_pairs),
                    )
                    if nxt not in seen:
                        seen.add(nxt)
                        frontier.append(nxt)

    return (
        True,
        total,
        "all mover/phase cut-feature equations hold at every reachable product state",
    )


def _solve_f2_unique(rows: Sequence[tuple[Sequence[int], int]]) -> list[int] | None:
    """Return the unique solution of an augmented F2 system, if it has one."""
    matrix = [list(coefficients) + [rhs] for coefficients, rhs in rows]
    columns = len(matrix[0]) - 1
    rank = 0
    for column in range(columns):
        pivot = next(
            (row for row in range(rank, len(matrix)) if matrix[row][column]),
            None,
        )
        if pivot is None:
            return None
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        for row in range(len(matrix)):
            if row != rank and matrix[row][column]:
                matrix[row] = [
                    left ^ right
                    for left, right in zip(matrix[row], matrix[rank])
                ]
        rank += 1
    if any(row[columns] for row in matrix[rank:]):
        return None
    return [matrix[row][columns] for row in range(columns)]


def check_a4_full_reconstruction(
    forward_n_shift: int = 0,
    backward_n_shift: int = 0,
    forward_boundary_shift: int = 0,
    backward_boundary_shift: int = 0,
    letter_count_flip: int = 0,
    successor_orientation_flip: bool = False,
    successor_phase_shift: int = 0,
) -> tuple[bool, int, str]:
    """Decide the six-variable reconstruction for every A4 word.

    The BFS is run independently for every mover ``g``.  Its state carries the
    meanings of all observables in the seven F2 equations:

    * ``x_p = N[g,p]`` and ``n_q = N'[gg,q]``;
    * the forward pair sums ``A_q``;
    * the forward successor-pair sums ``N'[g,h]``.  The corresponding pair
      sums on the reversed word are derived from these by
      ``A_rev[q] = successor[P-q]``;
    * total phase, first/last-letter flags, and ``|w|_g mod 2``.

    Thus the checker derives and solves the displayed linear system at every
    reachable state; it does not call the sampled ``reconstruct(w)`` routine.
    """
    _, _, _, sigma, eps, _, _ = a4_full_pieces()
    epsilon = [eps[letter] for letter in sigma]
    movers = [i for i, value in enumerate(epsilon) if value != 0]
    total = 0

    for g in movers:
        e = epsilon[g]
        # phase, last letter, phase before last, first-is-g, |w|_g,
        # x[3], n[3], predecessor-pair A[3], successor-pair S[3]
        start = (
            0,
            -1,
            0,
            0,
            0,
            (0, 0, 0),
            (0, 0, 0),
            (0, 0, 0),
            (0, 0, 0),
        )
        seen = {start}
        frontier = deque([start])
        while frontier:
            (
                phase,
                previous,
                previous_phase,
                first_g,
                letter_count,
                x,
                n,
                forward,
                successor,
            ) = frontier.popleft()
            total += 1
            backward = tuple(successor[(phase - q) % 3] for q in range(3))

            rows: list[tuple[list[int], int]] = []
            for p in range(3):
                coefficients = [0] * 6
                coefficients[p] = 1
                coefficients[3 + (p + e + forward_n_shift) % 3] = 1
                rhs = forward[(p + e) % 3]
                if p == forward_boundary_shift:
                    rhs ^= first_g
                rows.append((coefficients, rhs))
            for m in range(3):
                reverse_phase = (phase - e - m) % 3
                coefficients = [0] * 6
                coefficients[m] = 1
                coefficients[
                    3 + (m + 2 * e + backward_n_shift) % 3
                ] = 1
                rhs = backward[(reverse_phase + e) % 3]
                if reverse_phase == backward_boundary_shift and previous == g:
                    rhs ^= 1
                rows.append((coefficients, rhs))
            rows.append(
                ([1, 1, 1, 0, 0, 0], letter_count ^ (letter_count_flip & 1))
            )

            solution = _solve_f2_unique(rows)
            if solution is None or tuple(solution[:3]) != x:
                return (
                    False,
                    total,
                    f"reconstruction failed for mover {g} at reachable state {total}",
                )

            for letter in range(len(sigma)):
                next_phase = (phase + epsilon[letter]) % 3
                next_x = list(x)
                next_n = list(n)
                next_forward = list(forward)
                next_successor = list(successor)
                if letter == g:
                    next_x[phase] ^= 1
                    if previous == g:
                        next_n[next_phase] ^= 1
                    elif previous != -1:
                        next_forward[next_phase] ^= 1

                # A reverse predecessor pair (h,g) is exactly a forward
                # successor pair (g,h).  If g occurred at original phase m and
                # the total phase is P, its arrival phase in the reversed word
                # is P-m.  Carrying successor[m] makes this relation explicit
                # and avoids trusting a hand-written reverse-word transition.
                if successor_orientation_flip:
                    is_successor = previous != -1 and previous != g and letter == g
                else:
                    is_successor = previous == g and letter != g
                if is_successor:
                    next_successor[
                        (previous_phase + successor_phase_shift) % 3
                    ] ^= 1

                nxt = (
                    next_phase,
                    letter,
                    phase,
                    int(first_g or (previous == -1 and letter == g)),
                    letter_count ^ (letter == g),
                    tuple(next_x),
                    tuple(next_n),
                    tuple(next_forward),
                    tuple(next_successor),
                )
                if nxt not in seen:
                    seen.add(nxt)
                    frontier.append(nxt)

    return (
        True,
        total,
        "all eight mover reconstructions hold at every reachable observable state",
    )


def check_a4_full_token_aperiodicity(
    include_forbidden_repeat: bool = False,
) -> tuple[bool, int, str]:
    """Exhaust the transition monoid of every token DFA used by A4-FULL-01."""
    from scripts.research import a4_full12 as a4

    patterns = [None] + [("1", h) for h in a4.NONMOVERS]
    for g in a4.MOVERS:
        patterns.extend(("2", h, g) for h in a4.SIGMA if h != g)
    if include_forbidden_repeat:
        # This is the known periodic pure-repeat pattern excluded by the
        # construction.  Adding it must make the check fail.
        g = a4.MOVERS[0]
        patterns.append(("2", g, g))

    total = 0
    checked = 0
    for q in range(3):
        for pattern in patterns:
            states, transitions = a4.token_dfa(pattern, q=q)
            aperiodic, monoid_size = a4.is_aperiodic(states, transitions)
            total += monoid_size
            checked += 1
            if aperiodic is not True:
                return (
                    False,
                    max(total, 1),
                    f"periodic token DFA at phase {q}, pattern {pattern!r}",
                )
    return (
        True,
        total,
        f"all {checked} token DFAs have an exhaustively aperiodic transition monoid",
    )


def _a4_cut_component_dfa(q, pattern, start_phase, stop_at_cut):
    """DFA for the first cut, or for avoiding cuts, from a chosen start phase."""
    from scripts.research import a4_full12 as a4

    accept_cut = ("accept-cut",)
    dead = ("dead",)
    start = (start_phase, None)
    states = {start, accept_cut, dead}
    transitions = {}
    frontier = deque([start])
    cut = a4.CutPat(q, pattern)
    for terminal in (accept_cut, dead):
        for letter in a4.SIGMA:
            transitions[(terminal, letter)] = dead
    while frontier:
        phase, buffer = frontier.popleft()
        for letter in a4.SIGMA:
            next_phase = (phase + a4.EPS[letter]) % 3
            if next_phase == q:
                if cut.match(buffer, letter):
                    nxt = (next_phase, letter)
                else:
                    nxt = accept_cut
            else:
                nxt = (next_phase, letter)
            transitions[((phase, buffer), letter)] = nxt
            if nxt not in states:
                states.add(nxt)
                if nxt not in (accept_cut, dead):
                    frontier.append(nxt)
    regular = frozenset(state for state in states if state not in (accept_cut, dead))
    accepting = frozenset({accept_cut}) if stop_at_cut else regular
    return DFA(
        tuple(a4.SIGMA),
        frozenset(states),
        start,
        accepting,
        transitions,
    ).reachable()


def _a4_cut_parity_dfa(q, pattern, parity):
    """The direct CutPat machine accepting words with the selected cut parity."""
    from scripts.research import a4_full12 as a4

    start = (0, None, 0)
    states = {start}
    transitions = {}
    frontier = deque([start])
    cut = a4.CutPat(q, pattern)
    while frontier:
        phase, buffer, value = frontier.popleft()
        for letter in a4.SIGMA:
            next_phase = (phase + a4.EPS[letter]) % 3
            next_value = value
            if next_phase == q:
                if cut.match(buffer, letter):
                    next_buffer = letter
                else:
                    next_buffer = None
                    next_value ^= 1
            else:
                next_buffer = letter
            nxt = (next_phase, next_buffer, next_value)
            transitions[((phase, buffer, value), letter)] = nxt
            if nxt not in states:
                states.add(nxt)
                frontier.append(nxt)
    return DFA(
        tuple(a4.SIGMA),
        frozenset(states),
        start,
        frozenset(state for state in states if state[2] == parity),
        transitions,
    ).reachable()


def _dfa_equivalence_count(left: DFA, right: DFA) -> tuple[bool, int]:
    """Exact product equivalence together with the number of visited pairs."""
    if left.alphabet != right.alphabet:
        return False, 1
    start = (left.start, right.start)
    seen = {start}
    frontier = deque([start])
    while frontier:
        lstate, rstate = frontier.popleft()
        if (lstate in left.accept) != (rstate in right.accept):
            return False, len(seen)
        for letter in left.alphabet:
            nxt = (left.step(lstate, letter), right.step(rstate, letter))
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return True, len(seen)


def check_a4_full_token_factorization(
    pair_power: int = 2,
    include_zero_cut_case: bool = True,
) -> tuple[bool, int, str]:
    """Decide the unique-cut factorization and its star-free components.

    With ``X`` the reset-to-next-cut block, ``O`` the global opening block,
    ``V`` a reset tail with no further cut, and ``V0`` a global word with no
    cut, the cut-parity languages are

        odd  = O (X X)* V
        even = V0 union O X (X X)* V.

    The component transition monoids are exhausted to establish aperiodicity;
    the two displayed language equalities are then decided by DFA product
    reachability.  ``pair_power`` and ``include_zero_cut_case`` are false-claim
    controls, not changes to the equivalence checker.
    """
    from scripts.research import a4_full12 as a4

    patterns = [None] + [("1", h) for h in a4.NONMOVERS]
    for g in a4.MOVERS:
        patterns.extend(("2", h, g) for h in a4.SIGMA if h != g)

    total = 0
    checked = 0
    for q in range(3):
        for pattern in patterns:
            opening = _a4_cut_component_dfa(q, pattern, 0, True)
            block = _a4_cut_component_dfa(q, pattern, q, True)
            tail = _a4_cut_component_dfa(q, pattern, q, False)
            zero_cut = _a4_cut_component_dfa(q, pattern, 0, False)

            # Acceptance does not affect the transition monoid: block/tail and
            # opening/zero_cut share their respective transition structures.
            for component in (opening, block):
                ok, monoid_size = a4.is_aperiodic(
                    list(component.states), dict(component.transition)
                )
                total += monoid_size
                if ok is not True:
                    return (
                        False,
                        max(total, 1),
                        f"non-aperiodic cut component at q={q}, pattern={pattern!r}",
                    )

            repeated = block
            for _ in range(1, pair_power):
                repeated = dfa_concat(repeated, block)
            loop = dfa_star(repeated)
            odd_formula = dfa_concat(dfa_concat(opening, loop), tail)
            positive_even = dfa_concat(
                dfa_concat(dfa_concat(opening, block), loop), tail
            )
            even_formula = (
                dfa_product(zero_cut, positive_even, lambda left, right: left or right)
                if include_zero_cut_case
                else positive_even
            )

            odd_ok, odd_states = _dfa_equivalence_count(
                odd_formula, _a4_cut_parity_dfa(q, pattern, 1)
            )
            even_ok, even_states = _dfa_equivalence_count(
                even_formula, _a4_cut_parity_dfa(q, pattern, 0)
            )
            total += odd_states + even_states
            checked += 2
            if not odd_ok or not even_ok:
                return (
                    False,
                    max(total, 1),
                    f"cut factorization failed at q={q}, pattern={pattern!r}",
                )

    return (
        True,
        total,
        f"both parity formulas verified for all {checked // 2} cut patterns",
    )


def check_a4_full_alphabet(
    omit_last_letter: bool = False,
    decomposition_shift: int = 0,
) -> tuple[bool, int, str]:
    """Check that the concrete twelve letters are exactly A4, with its v*t^e split."""
    import itertools

    pmul, _, tpow, sigma, eps, vpart, _ = a4_full_pieces()
    concrete = list(sigma[:-1] if omit_last_letter else sigma)

    def even(permutation) -> bool:
        inversions = sum(
            permutation[i] > permutation[j]
            for i in range(4)
            for j in range(i + 1, 4)
        )
        return inversions % 2 == 0

    a4_elements = {
        permutation
        for permutation in itertools.permutations(range(4))
        if even(permutation)
    }
    if set(concrete) != a4_elements or len(concrete) != len(set(concrete)):
        return False, 24, "the concrete alphabet is not exactly the 12 even permutations"
    for letter in concrete:
        rebuilt = pmul(
            vpart[letter],
            tpow[(eps[letter] + decomposition_shift) % 3],
        )
        if rebuilt != letter:
            return False, 24, "the v*t^e decomposition failed"
    return True, 24, "the letters are exactly A4 and every v*t^e decomposition is correct"


def check_a4_full_step4(shift: int = 0, phase_stride: int = 1) -> tuple[bool, int, str]:
    """Decide `S(w) . t^P = phi(w)` for all w.

    `shift` displaces the tau exponent and `phase_stride` the phase advance;
    either one makes the formula false, so both serve as controls on the claim
    rather than on the search.
    """
    pmul, ident, tpow, sigma, eps, vpart, tau_pow = a4_full_pieces()

    start = ((0, ident), ident)  # ((phase, V4 sum), Cayley state)
    seen = {start}
    frontier = deque([start])
    checked = 0
    while frontier:
        (phase, acc), prod = frontier.popleft()
        # The identity must hold at every reachable state, i.e. for every word.
        if pmul(acc, tpow[phase]) != prod:
            return False, checked, f"violated after a word reaching (phase={phase})"
        checked += 1
        for g in sigma:
            nxt = (
                (
                    (phase + phase_stride * eps[g]) % 3,
                    pmul(acc, tau_pow(vpart[g], phase + shift)),
                ),
                pmul(prod, g),
            )
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return True, checked, f"identity holds at all {checked} reachable product states"


def check_a4_full() -> None:
    print("\n=== A4-FULL-01: full-alphabet finite checks ===")

    ok, universe, detail = check_a4_full_alphabet()
    alphabet_check = RUN.add(
        exhaustive(
            "A4-FULL-01 concrete alphabet",
            "A4-FULL-01/alphabet",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "remove one of the twelve letters",
                    "the claim that Sigma contains every A4 element",
                    rejected=not check_a4_full_alphabet(omit_last_letter=True)[0],
                ),
                Control(
                    "shift every exponent in v*t^e by 1",
                    "the unique v*t^e decomposition of each letter",
                    rejected=not check_a4_full_alphabet(decomposition_shift=1)[0],
                ),
            ],
        )
    )

    ok, universe, detail = check_a4_full_token_aperiodicity()
    token_check = RUN.add(
        exhaustive(
            "A4-FULL-01 token aperiodicity",
            "A4-FULL-01/token-aperiodicity",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "add the forbidden pure-repeat pattern gg",
                    "the excluded h = g pattern is added to the token family",
                    rejected=not check_a4_full_token_aperiodicity(
                        include_forbidden_repeat=True
                    )[0],
                )
            ],
        )
    )

    ok, universe, detail = check_a4_full_token_factorization()
    factorization_check = RUN.add(
        exhaustive(
            "A4-FULL-01 token factorization",
            "A4-FULL-01/token-factorization",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "replace the even block pair XX by a single block X",
                    "the block repeated under the unique Kleene star",
                    rejected=not check_a4_full_token_factorization(pair_power=1)[0],
                ),
                Control(
                    "delete the zero-cut case from the even language",
                    "the V0 summand in the even cut-parity formula",
                    rejected=not check_a4_full_token_factorization(
                        include_zero_cut_case=False
                    )[0],
                ),
            ],
        )
    )

    ok, universe, detail = check_a4_full_feature_equations()
    feature_check = RUN.add(
        exhaustive(
            "A4-FULL-01 feature equations",
            "A4-FULL-01/feature-equations",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "pattern target shifted to the next alphabet letter",
                    "the terminal g in every mover pattern hg",
                    rejected=not check_a4_full_feature_equations(
                        pattern_target_shift=1
                    )[0],
                ),
                Control(
                    "claimed pair-arrival phase shifted by 1",
                    "the q index of the mover-pair sum N'[hg,q]",
                    rejected=not check_a4_full_feature_equations(
                        claimed_arrival_shift=1
                    )[0],
                ),
                Control(
                    "nonmover exception changed to the next alphabet letter",
                    "the exceptional h in each one-letter pattern",
                    rejected=not check_a4_full_feature_equations(
                        nonmover_exception_shift=1
                    )[0],
                ),
            ],
        )
    )

    ok, universe, detail = check_a4_full_reconstruction()
    reconstruction_check = RUN.add(
        exhaustive(
            "A4-FULL-01 reconstruction",
            "A4-FULL-01/reconstruction",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "forward n index shifted by 1",
                    "n_(p+epsilon) in the forward equations",
                    rejected=not check_a4_full_reconstruction(
                        forward_n_shift=1
                    )[0],
                ),
                Control(
                    "backward n index shifted by 1",
                    "n_(m+2*epsilon) in the backward equations",
                    rejected=not check_a4_full_reconstruction(
                        backward_n_shift=1
                    )[0],
                ),
                Control(
                    "first-letter boundary moved from phase 0 to phase 1",
                    "the s*[p=0] term in the forward equations",
                    rejected=not check_a4_full_reconstruction(
                        forward_boundary_shift=1
                    )[0],
                ),
                Control(
                    "last-letter boundary moved from phase 0 to phase 1",
                    "the st*[r=0] term in the backward equations",
                    rejected=not check_a4_full_reconstruction(
                        backward_boundary_shift=1
                    )[0],
                ),
                Control(
                    "letter-count parity flipped",
                    "the right-hand side |w|_g mod 2 of the sum equation",
                    rejected=not check_a4_full_reconstruction(
                        letter_count_flip=1
                    )[0],
                ),
                Control(
                    "successor-pair orientation reversed",
                    "the original pair (g,h) corresponding to reverse (h,g)",
                    rejected=not check_a4_full_reconstruction(
                        successor_orientation_flip=True
                    )[0],
                ),
                Control(
                    "successor-pair source phase shifted by 1",
                    "the original phase m in A_rev[q] = successor[P-q]",
                    rejected=not check_a4_full_reconstruction(
                        successor_phase_shift=1
                    )[0],
                ),
            ],
        )
    )
    step3_check = RUN.add(
        conjunction(
            "A4-FULL-01 step [3]",
            "A4-FULL-01/step-3",
            parts=[feature_check, reconstruction_check],
            detail=(
                "certified cut features determine every N[g,p] bit for every word"
            ),
            rationale=(
                "the feature equations connect the actual CutPat outputs to the "
                "event sums, and the unique GF(2) system reconstructs all target "
                "bits; notes/a4_full_alphabet_exact.md §§5–6 proves the reversal "
                "transport and shows that these are exactly the inputs consumed "
                "by the solver"
            ),
        )
    )

    ok, universe, detail = check_a4_full_step4()
    step4_check = RUN.add(
        exhaustive(
            "A4-FULL-01 step [4]",
            "A4-FULL-01/step-4",
            passed=ok,
            universe=universe,
            detail=detail,
            controls=[
                Control(
                    "tau exponent shifted by 1",
                    "the phase at which tau acts in the closed form",
                    rejected=not check_a4_full_step4(shift=1)[0],
                ),
                Control(
                    "phase advance doubled",
                    "the rate at which the phase P advances",
                    rejected=not check_a4_full_step4(phase_stride=2)[0],
                ),
            ],
        )
    )
    # This conjunction deliberately has its own claim id.  The finite checks
    # below do not themselves decide Schützenberger's
    # aperiodic-monoid-to-star-free theorem or the structural closure argument
    # that assembles the final generalized expression, so naming this verdict
    # `A4-FULL-01` would overstate the scope of the computation.
    RUN.add(
        conjunction(
            "A4-FULL-FINITE-CORE-01",
            "A4-FULL-FINITE-CORE-01",
            parts=[
                alphabet_check,
                token_check,
                factorization_check,
                step3_check,
                step4_check,
            ],
            detail=(
                "all finite automaton, GF(2), and A4 multiplication obligations "
                "used by the proposed full-alphabet proof have been decided"
            ),
            rationale=(
                "the concrete alphabet, token aperiodicity and factorization, "
                "feature equations, unique GF(2) reconstruction, and group formula "
                "are exhaustive. notes/a4_full_alphabet_exact.md §§3–7 supplies "
                "the separate human composition with Schutzenberger's theorem and "
                "the Boolean/reversal closure lemmas; this verdict does not claim "
                "to decide that mathematical composition."
            ),
        )
    )


# ==========================================================================
# WATOM-45-01: the 20 staged-count atoms {w : N_r(w) = h mod 5}
# ==========================================================================
#
# `scripts/research/f20_word_problem.py` check [3b] compares each compiled atom with the
# direct staged count on all 8,191 words of length <= 12. The target is a
# regular language with an obvious 20-state automaton — (b-count mod 4, N_r mod
# 5) — so the comparison can simply be decided instead.


def check_watom() -> None:
    print("\n=== WATOM-45-01: the 20 staged-count atoms N_r = h (mod 5) ===")
    from scripts.research.f20_word_problem import W, AL, compile_dfa, dfa, d_min, height
    from scripts.research.f20_word_problem import equivalence_counterexample

    def staged_target(r: int, h: int):
        """(b-count mod 4, N_r mod 5); `a` counts only while the phase is r."""
        index = {(p, c): p * 5 + c for p in range(4) for c in range(5)}
        transitions = [None] * 20
        for (p, c), i in index.items():
            transitions[i] = {
                "a": index[(p, (c + 1) % 5 if p == r else c)],
                "b": index[((p + 1) % 4, c)],
            }
        accept = [index[(p, h)] for p in range(4)]
        return d_min(dfa(transitions, index[(0, 0)], accept))

    assert set(AL) == {"a", "b"}
    bad = []
    for r in range(4):
        for h in range(5):
            witness = equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, h))
            if witness is not None:
                bad.append((r, h, witness))

    # Controls on the claim: each atom is compared against the target for the
    # wrong residue, and against the target for the wrong phase. Both are false
    # statements about the same 20 atoms, so a checker that accepts either has
    # not established the correct one.
    missed_residue = [
        (r, h)
        for r in range(4)
        for h in range(5)
        if equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, (h + 1) % 5))
        is None
    ]
    missed_phase = [
        (r, h)
        for r in range(4)
        for h in range(5)
        if equivalence_counterexample(compile_dfa(W[r][h]), staged_target((r + 1) % 4, h))
        is None
    ]
    equal = RUN.add(
        exhaustive(
            "WATOM-45-01 atoms equal their staged-count DFAs",
            "WATOM-45-01/equality",
            passed=not bad,
            universe=20,
            detail=(
                "all 20 atoms proved equal to their 20-state staged-count DFAs by "
                "complete product reachability"
                if not bad
                else f"{len(bad)} atoms disagree, e.g. {bad[0]}"
            ),
            controls=[
                Control(
                    "residue h -> h+1",
                    "the residue class each atom counts",
                    rejected=not missed_residue,
                ),
                Control(
                    "phase r -> r+1",
                    "the phase at which each atom counts",
                    rejected=not missed_phase,
                ),
            ],
        )
    )

    # The row claims a height, so a height has to be computed. `height` is the
    # syntactic star height of the expression tree; the control is the same
    # measurement on an expression with a star nested inside a star, which must
    # come out above 1 or the measurement is not measuring.
    heights = sorted({height(W[r][h]) for r in range(4) for h in range(5)})
    from scripts.research.f20_word_problem import star as _star, union as _union

    nested = _star(_star(W[0][0]))
    tall = RUN.add(
        exhaustive(
            "WATOM-45-01 atoms have star height 1",
            "WATOM-45-01/height",
            passed=heights == [1],
            universe=20,
            detail=f"syntactic star height of all 20 atoms: {heights}",
            controls=[
                Control(
                    "a star nested inside a star",
                    "the expression whose height is measured",
                    rejected=height(nested) > 1,
                )
            ],
        )
    )
    RUN.add(
        conjunction(
            "WATOM-45-01",
            "WATOM-45-01",
            parts=[equal, tall],
            detail="each atom is the staged-count language, and has star height 1",
            rationale=(
                "the row asserts of the 20 atoms that each *is* the staged-count "
                "language and that each has height <= 1; both are decided, for all 20"
            ),
        )
    )


# ==========================================================================
# LAAB-04-01 and THOMAS-D2-02: arithmetic reductions, decided
# ==========================================================================
#
# Both rows have proved atoms and a *sampled composite*. Each composite is an
# integer identity holding for every word. `decide_linear_identity` takes the
# meaning of each quantity and the coefficients of the identity and derives the
# search itself, so the identity's constants stay perturbable — which is exactly
# what the first version of this file lost.


def check_laab() -> None:
    print("\n=== LAAB-04-01: binom(w,aab) = M1 + 2*M2 (mod 4) ===")
    # Control state: (#a so far mod 8, binom(#a, 2) mod 4). Every quantity that
    # appears in the identity is an observable, never a pre-combined defect.
    RUN.add(
        decide_linear_identity(
            "LAAB-04-01 composite",
            "LAAB-04-01/identity",
            alphabet="ab",
            control_start=(0, 0),
            control_step=lambda s, x: ((s[0] + 1) % 8, (s[1] + s[0]) % 4) if x == "a" else s,
            observables=[
                Observable("binom_aab", lambda s, x, t: s[1] if x == "b" else 0),
                Observable("m1", lambda s, x, t: 1 if (x == "b" and s[0] % 4 in (2, 3)) else 0),
                Observable(
                    "m2", lambda s, x, t: 1 if (x == "b" and s[0] % 8 in (3, 4, 5, 6)) else 0
                ),
            ],
            coefficients={"binom_aab": 1, "m1": -1, "m2": -2},
            modulus=4,
            detail=(
                "M1 = N_2^(4)+N_3^(4) mod 4, M2 = N_3^(8)+N_4^(8)+N_5^(8)+N_6^(8) mod 2"
            ),
        )
    )


def check_thomas() -> None:
    print("\n=== THOMAS-D2-02: the flat token-counting identity ===")
    # Control state: the parse state of the prefix code {b, aa, ab}.
    # 0 = between tokens, 1 = one `a` read and the token is not yet complete.
    RUN.add(
        decide_linear_identity(
            "THOMAS-D2-02 identity",
            "THOMAS-D2-02/identity",
            alphabet="ab",
            control_start=0,
            control_step=lambda p, x: 1 if (p == 0 and x == "a") else 0,
            observables=[
                Observable("n_ab", lambda p, x, q: 1 if (p == 1 and x == "b") else 0),
                Observable("len_a", lambda p, x, q: 1 if x == "a" else 0),
                Observable("len_b", lambda p, x, q: 1 if x == "b" else 0),
                Observable("n_tok", lambda p, x, q: 0 if (p == 0 and x == "a") else 1),
                Observable("tail", lambda p, x, q: 0, terminal=lambda p: 1 if p == 1 else 0),
            ],
            coefficients={"n_ab": 1, "len_a": -1, "len_b": -2, "n_tok": 2, "tail": 1},
            detail=(
                "#ab = |w|_a + 2*|w|_b - 2*#tok - [tail=a] "
                "over the prefix code {b, aa, ab}"
            ),
        )
    )


def main() -> int:
    print("Completeness upgrades for rows demoted by the 2026-07-25 audit.")
    check_a5()
    check_a4_full()
    check_watom()
    check_laab()
    check_thomas()
    return RUN.finish()


if __name__ == "__main__":
    raise SystemExit(main())
