#!/usr/bin/env python3
"""Exact audit of four-letter full-phase sections in ``F_20``.

The theorem ``F20-ALPH4-CLASS-01`` is proved without computation in
``notes/f20_alphabetic_reduction.md`` section 11.  This program traverses the
entire finite object appearing in that proof: all ``5^4`` sections of the
phase quotient, all five complements, and all automorphisms obtained from the
images of the standard generators.  It samples no words and makes no
generalized-star-height claim.
"""

from __future__ import annotations

import itertools
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.ci.f20_phase_rigidity import (
    ELEMENTS,
    IDENTITY,
    base,
    generated_subgroup,
    order,
    power,
)


STANDARD_A = (1, 1)  # phase 0, order 5
STANDARD_B = (2, 0)  # phase 1, order 4


def phase_sections() -> tuple[frozenset[tuple[int, int]], ...]:
    """All subsets containing exactly one element in each quotient phase."""

    return tuple(
        frozenset((base.POWERS_OF_TWO[phase], betas[phase]) for phase in range(4))
        for betas in itertools.product(range(5), repeat=4)
    )


def complements() -> frozenset[frozenset[tuple[int, int]]]:
    """The five order-four complements, generated by the phase-one elements."""

    phase_one = (g for g in ELEMENTS if base.EPSILON[g] == 1)
    return frozenset(generated_subgroup((g,)) for g in phase_one)


def automorphisms() -> tuple[dict[tuple[int, int], tuple[int, int]], ...]:
    """Exhaust all order-compatible images of the standard presentation."""

    candidates_a = tuple(g for g in ELEMENTS if order(g) == 5)
    candidates_b = tuple(g for g in ELEMENTS if order(g) == 4)
    found = []
    for image_a, image_b in itertools.product(candidates_a, candidates_b):
        mapping = {
            g: base.compose(
                power(image_b, base.EPSILON[g]), power(image_a, g[1])
            )
            for g in ELEMENTS
        }
        if len(set(mapping.values())) != len(ELEMENTS):
            continue
        if not all(
            mapping[base.compose(x, y)] == base.compose(mapping[x], mapping[y])
            for x in ELEMENTS
            for y in ELEMENTS
        ):
            continue
        found.append(mapping)
    return tuple(found)


def projective_orbit_key(section: frozenset[tuple[int, int]]):
    """Canonical point of P^2(F_5), or ``None`` for a complement."""

    betas = tuple(next(g[1] for g in section if base.EPSILON[g] == phase)
                  for phase in range(4))
    vector = (betas[0], (betas[2] - 3 * betas[1]) % 5,
              (betas[3] - 2 * betas[1]) % 5)
    if vector == (0, 0, 0):
        return None
    leading = next(x for x in vector if x != 0)
    scale = pow(leading, -1, 5)
    return tuple(scale * x % 5 for x in vector)


def audit() -> dict[str, object]:
    sections = phase_sections()
    complement_sets = complements()
    autos = automorphisms()

    subgroup_orders = {4: 0, 20: 0}
    exceptional = set()
    for section in sections:
        size = len(generated_subgroup(section))
        subgroup_orders[size] = subgroup_orders.get(size, 0) + 1
        if size != 20:
            exceptional.add(section)

    seen: set[frozenset[tuple[int, int]]] = set()
    orbit_profile: dict[tuple[int, int], int] = {}
    orbit_keys = set()
    invariant_matches_orbits = True
    for section in sections:
        if section in seen:
            continue
        orbit = {
            frozenset(mapping[g] for g in section)
            for mapping in autos
        }
        seen.update(orbit)
        key = (len(orbit), len(generated_subgroup(section)))
        orbit_profile[key] = orbit_profile.get(key, 0) + 1
        projective_keys = {projective_orbit_key(member) for member in orbit}
        invariant_matches_orbits &= len(projective_keys) == 1
        orbit_keys.update(projective_keys)

    phase_preserved = all(
        base.EPSILON[mapping[g]] == base.EPSILON[g]
        for mapping in autos
        for g in ELEMENTS
    )
    identity_containing = sum(IDENTITY in section for section in sections)
    return {
        "sections": len(sections),
        "distinct_sections": len(set(sections)),
        "subgroup_orders": subgroup_orders,
        "complements": len(complement_sets),
        "exceptional_match_complements": exceptional == set(complement_sets),
        "automorphism_candidates": 4 * 10,
        "automorphisms": len(autos),
        "phase_preserved": phase_preserved,
        "orbits": len(orbit_profile) and sum(orbit_profile.values()),
        "orbit_profile": orbit_profile,
        "orbit_coverage": len(seen),
        "projective_keys": len(orbit_keys - {None}),
        "invariant_matches_orbits": invariant_matches_orbits,
        "identity_containing": identity_containing,
    }


def main() -> int:
    result = audit()
    expected = {
        "sections": 625,
        "distinct_sections": 625,
        "subgroup_orders": {4: 5, 20: 620},
        "complements": 5,
        "exceptional_match_complements": True,
        "automorphism_candidates": 40,
        "automorphisms": 20,
        "phase_preserved": True,
        "orbits": 32,
        "orbit_profile": {(5, 4): 1, (20, 20): 31},
        "orbit_coverage": 625,
        "projective_keys": 31,
        "invariant_matches_orbits": True,
        "identity_containing": 125,
    }
    if result != expected:
        print("F20 four-letter classification: FAIL")
        print(result)
        return 1

    # Claim-level negative controls: each false strengthening is rejected by
    # an independently counted field of the exact traversal.
    controls = {
        "every full-phase section generates": result["subgroup_orders"] != {20: 625},
        "all generating sections are one automorphism orbit":
            result["orbit_profile"] != {(5, 4): 1, (620, 20): 1},
        "the exceptions are exactly the identity-containing sections":
            result["identity_containing"] != result["subgroup_orders"][4],
        "all order-compatible generator images are automorphisms":
            result["automorphisms"] != result["automorphism_candidates"],
    }
    if not all(controls.values()):
        print("F20 four-letter classification controls: FAIL")
        print(controls)
        return 1

    print(
        "F20 four-letter classification: PASS; "
        "625 sections = 620 generating + 5 complements; "
        "Aut(F20): 31 free generating orbits + 1 complement orbit"
    )
    print("negative controls: 4/4 rejected")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
