import GSH.Groups.SmallOrder
import GSH.Transfer
import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.GroupTheory.OrderOfElement

/-!
# The split-extension presentation of `S₃`

This file formalizes only the group-theoretic bridge

`A₃ ⋊ C₂ ≃ S₃`.

It does not prove that the semidirect product has the height-one property.
That language-theoretic lift remains `L-ABC2-001` / `M-PST-003`.
-/

set_option autoImplicit false

namespace GSH

universe u

/-- The transposition `(0 1)` in `S₃`. -/
def s3Swap : Equiv.Perm (Fin 3) := Equiv.swap 0 1

/-- The order-two subgroup of `S₃` generated by `(0 1)`. -/
def s3Reflection : Subgroup (Equiv.Perm (Fin 3)) :=
  Subgroup.zpowers s3Swap

/-- The chosen transposition has order two. -/
theorem s3Swap_order : orderOf s3Swap = 2 := by
  apply orderOf_eq_prime
  · ext i
    fin_cases i <;> rfl
  · intro h
    have hi := DFunLike.congr_fun h (0 : Fin 3)
    simp [s3Swap] at hi

/-- The alternating subgroup `A₃` has order three. -/
theorem s3_alternating_card : Nat.card (alternatingGroup (Fin 3)) = 3 := by
  rw [Nat.card_eq_fintype_card, card_alternatingGroup]
  norm_num [Nat.factorial]

/-- The subgroup generated by the chosen transposition has order two. -/
theorem s3_reflection_card : Nat.card s3Reflection = 2 := by
  rw [s3Reflection, Nat.card_zpowers, s3Swap_order]

/-- The symmetric group on three points has order six. -/
theorem s3_card : Nat.card (Equiv.Perm (Fin 3)) = 6 := by
  rw [Nat.card_eq_fintype_card, Fintype.card_perm]
  norm_num [Nat.factorial]

/-- `A₃` and the chosen reflection subgroup are complementary in `S₃`. -/
theorem s3_complement :
    (alternatingGroup (Fin 3)).IsComplement' s3Reflection := by
  apply Subgroup.isComplement'_of_coprime
  · rw [s3_alternating_card, s3_reflection_card, s3_card]
  · rw [s3_alternating_card, s3_reflection_card]
    norm_num

/-- Conjugation by the chosen reflection subgroup on the normal subgroup `A₃`. -/
def s3ConjugationAction :
    s3Reflection →* MulAut (alternatingGroup (Fin 3)) :=
  ((alternatingGroup (Fin 3)).normalizerMonoidHom).comp
    (Subgroup.inclusion (show
      s3Reflection ≤ Subgroup.normalizer (alternatingGroup (Fin 3)) by
        rw [(alternatingGroup (Fin 3)).normalizer_eq_top]
        exact le_top))

/-- The concrete split-extension presentation `A₃ ⋊ C₂ ≃ S₃`. -/
noncomputable def s3SemidirectEquiv :
    (alternatingGroup (Fin 3)) ⋊[s3ConjugationAction]
      s3Reflection ≃* Equiv.Perm (Fin 3) :=
  SemidirectProduct.mulEquivSubgroup s3_complement

/-- A height-one theorem for the concrete semidirect product would imply the
exact `S₃` target.  This theorem transports such a proof; it does not supply
the still-open premise. -/
theorem heightOne_S3_of_semidirect
    (h : HeightOneForGroup.{u}
      ((alternatingGroup (Fin 3)) ⋊[s3ConjugationAction] s3Reflection)) :
    HeightOneForGroup.{u} (Equiv.Perm (Fin 3)) :=
  HeightOneForGroup.of_mulEquiv s3SemidirectEquiv.symm h

end GSH
