#!/usr/bin/env python3
"""Turn sampled checks into decided ones (2026-07-25 completeness audit).

The audit found ledger rows whose final step was bounded-length agreement plus
random words. A sample can refute but never establish, so those rows were set to
`EMPIRICAL`. This script re-establishes them by reducing each claim to a finite
object and traversing it exhaustively, which is what `COMPUTED` now requires.

Two shapes of claim appear, and they need different machinery:

  * "this height-1 expression denotes exactly that language" — decided by
    compiling the expression to a DFA and running product reachability against
    the target DFA (`tools/regex_cert.py`, the same checker `scripts/check.sh`
    already runs on the stored certificates).  `A5-GEN145-01`.

  * "this closed-form function of the automaton state equals the group element"
    — decided by a BFS over the product of the two automata, checking the
    identity at every reachable pair.  `A4-FULL-01` step [4].

Every check here carries a NEGATIVE CONTROL: the same machinery is run on a
deliberately broken input and must reject it. A checker that cannot fail proves
nothing, which is research rule 7 and the reason this file exists.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.regex_cert import DFA, compile_regex, equivalence_witness, parse_regex

FAILURES: list[str] = []


def report(name: str, ok: bool, detail: str) -> None:
    print(f"  [{'ok' if ok else 'FAIL'}] {name}: {detail}", flush=True)
    if not ok:
        FAILURES.append(name)


# --------------------------------------------------------------------------
# Generalized-expression constructors (JSON shape of tools/regex_cert.py)
# --------------------------------------------------------------------------

EMPTY = {"op": "empty"}
EPS = {"op": "eps"}


def lit(x: str) -> dict:
    return {"op": "letter", "value": x}


def cat(*args: dict) -> dict:
    return {"op": "concat", "args": list(args)} if args else EPS


def alt(*args: dict) -> dict:
    return {"op": "union", "args": list(args)}


def compl(arg: dict) -> dict:
    return {"op": "compl", "arg": arg}


def star(arg: dict) -> dict:
    return {"op": "star", "arg": arg}


UNIV = compl(EMPTY)  # Sigma*, star height 0


def avoid(x: str) -> dict:
    """Words containing no `x`, i.e. the star-free language usually written x'*.

    Written with complement so that it costs star height ZERO. Writing it as a
    star instead is what pushes these constructions to height 2.
    """
    return compl(cat(UNIV, lit(x), UNIV))


def inter(*args: dict) -> dict:
    return compl(alt(*[compl(a) for a in args]))


def cayley_dfa(alphabet, images, mul, ident, accept=None) -> DFA:
    """Cayley automaton of the group generated by `images`, from the identity."""
    states = {ident}
    frontier = deque([ident])
    transition = {}
    while frontier:
        g = frontier.popleft()
        for x in alphabet:
            h = mul(g, images[x])
            transition[(g, x)] = h
            if h not in states:
                states.add(h)
                frontier.append(h)
    acc = frozenset({ident} if accept is None else accept)
    dfa = DFA(tuple(alphabet), frozenset(states), ident, acc, transition)
    dfa.validate()
    return dfa


def decide_equivalence(name: str, expr: dict, alphabet, target: DFA, height: int) -> None:
    """Complete finite proof that `expr` denotes exactly `target`'s language."""
    parsed = parse_regex(expr, alphabet)
    got_height = parsed.star_height()
    if got_height > height:
        report(name, False, f"star height {got_height} exceeds the claimed {height}")
        return
    compiled = compile_regex(parsed, alphabet)
    witness = equivalence_witness(compiled, target)
    if witness is not None:
        report(name, False, f"NOT equivalent; witness {''.join(witness)!r}")
        return
    report(
        name,
        True,
        f"exact DFA equivalence by product reachability, no sampling "
        f"(height {got_height} <= {height}; target {len(target.states)} states)",
    )


def expect_rejection(name: str, expr: dict, alphabet, target: DFA) -> None:
    """Negative control: the checker must find a counterexample."""
    compiled = compile_regex(parse_regex(expr, alphabet), alphabet)
    witness = equivalence_witness(compiled, target)
    report(
        f"{name} [negative control]",
        witness is not None,
        f"broken variant rejected with witness {''.join(witness)!r}"
        if witness is not None
        else "BROKEN VARIANT ACCEPTED — the checker is not discriminating",
    )


# ==========================================================================
# A5-GEN145-01
# ==========================================================================


def a5_target() -> DFA:
    def pmul(p, q):
        return tuple(q[i] for i in p)

    return cayley_dfa(
        ("a", "b"),
        {"a": (1, 2, 0, 3, 4), "b": (3, 1, 2, 4, 0)},  # (123), (145)
        pmul,
        (0, 1, 2, 3, 4),
    )


def a5_expression() -> dict:
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")  # a* and b*, both star-free
    C = alt(cat(a, Bs, a, Bs, a), cat(b, As, b, As, b))
    k1 = star(C)
    k2 = alt(Bs, cat(Bs, a, Bs, a, star(C), a, Bs))
    k3 = alt(Bs, cat(Bs, a, star(C), a, Bs, a, Bs))
    return inter(k1, k2, k3)


def check_a5() -> None:
    print("\n=== A5-GEN145-01: phi(a)=(123), phi(b)=(145), L = phi^-1(e) ===")
    target = a5_target()
    report(
        "generated group order",
        len(target.states) == 60,
        f"|<(123),(145)>| = {len(target.states)} (expect 60 = |A5|)",
    )
    decide_equivalence("A5-GEN145-01", a5_expression(), ("a", "b"), target, height=1)

    # Negative control: drop one disjunct of the first-return code C.
    a, b = lit("a"), lit("b")
    As, Bs = avoid("b"), avoid("a")
    broken_C = cat(a, Bs, a, Bs, a)  # the `b a* b a* b` half removed
    broken = inter(
        star(broken_C),
        alt(Bs, cat(Bs, a, Bs, a, star(broken_C), a, Bs)),
        alt(Bs, cat(Bs, a, star(broken_C), a, Bs, a, Bs)),
    )
    expect_rejection("A5-GEN145-01", broken, ("a", "b"), target)


# ==========================================================================
# A4-FULL-01, step [4]: group element from (P, N[g,p] mod 2)
# ==========================================================================
#
# `scripts/a4_full12.py` checks this on 20,000 random words. It is decidable.
#
# Write g = v . t^e with v in V4 and e = eps(g) in Z/3. `direct_all` flips the
# bit N[g,p] at the phase p *before* reading g, and
#
#     group_from_counts(N, P) = ( SUM_{(g,p): N[g,p]=1} tau^p(V(g)) ) . t^P
#
# where the sum is in V4. V4 is elementary abelian, so the sum is order-
# independent and a repeated occurrence cancels exactly as the mod-2 bit does.
# Therefore the whole right-hand side is computed incrementally by a 12-state
# automaton on (phase, running V4 sum), and the claim
#
#     for every w:  S(w) . t^{P(w)} = phi(w)
#
# is decided by a BFS over the 12 x 12 product with the Cayley automaton.


def a4_full_pieces():
    def pmul(p, q):
        return tuple(q[i] for i in p)

    ident = (0, 1, 2, 3)
    t = (1, 2, 0, 3)
    t2 = pmul(t, t)
    v4 = [ident, (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)]
    sigma, eps, vpart = [], {}, {}
    for v in v4:
        for e, te in ((0, ident), (1, t), (2, t2)):
            g = pmul(v, te)
            sigma.append(g)
            eps[g] = e
            vpart[g] = v

    def tau(v):
        return pmul(pmul(t, v), t2)

    def tau_pow(v, k):
        for _ in range(k % 3):
            v = tau(v)
        return v

    return pmul, ident, (ident, t, t2), sigma, eps, vpart, tau_pow


def check_a4_full_step4(shift: int = 0) -> tuple[bool, str]:
    """Decide `S(w) . t^P = phi(w)` for all w. `shift` breaks it on purpose."""
    pmul, ident, tpow, sigma, eps, vpart, tau_pow = a4_full_pieces()

    start = ((0, ident), ident)  # ((phase, V4 sum), Cayley state)
    seen = {start}
    frontier = deque([start])
    checked = 0
    while frontier:
        (phase, acc), prod = frontier.popleft()
        # The identity must hold at every reachable state, i.e. for every word.
        if pmul(acc, tpow[phase]) != prod:
            return False, f"violated after a word reaching (phase={phase})"
        checked += 1
        for g in sigma:
            nxt = (
                ((phase + eps[g]) % 3, pmul(acc, tau_pow(vpart[g], phase + shift))),
                pmul(prod, g),
            )
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return True, f"identity holds at all {checked} reachable product states"


def check_a4_full() -> None:
    print("\n=== A4-FULL-01 step [4]: group element from (P, N[g,p] mod 2) ===")
    ok, detail = check_a4_full_step4()
    report("A4-FULL-01 step [4]", ok, detail + " (complete finite proof, no sampling)")

    # Negative control: the same BFS with the phase exponent shifted by one.
    broken_ok, broken_detail = check_a4_full_step4(shift=1)
    report(
        "A4-FULL-01 step [4] [negative control]",
        not broken_ok,
        f"tau exponent shifted by 1 is rejected — {broken_detail}"
        if not broken_ok
        else "SHIFTED FORMULA ACCEPTED — the BFS is not discriminating",
    )


# ==========================================================================
# WATOM-45-01: the 20 staged-count atoms {w : N_r(w) = h mod 5}
# ==========================================================================
#
# `scripts/f20_word_problem.py` check [3b] compares each compiled atom with the
# direct staged count on all 8,191 words of length <= 12. The target is a
# regular language with an obvious 20-state automaton — (b-count mod 4, N_r mod
# 5) — so the comparison can simply be decided instead.


def check_watom() -> None:
    print("\n=== WATOM-45-01: the 20 staged-count atoms N_r = h (mod 5) ===")
    from scripts.f20_word_problem import W, AL, compile_dfa, dfa, d_min
    from scripts.f20_word_problem import equivalence_counterexample

    def staged_target(r: int, h: int):
        """(b-count mod 4, N_r mod 5); `a` counts only while the phase is r."""
        index = {(p, c): p * 5 + c for p in range(4) for c in range(5)}
        transitions = [None] * 20
        for (p, c), i in index.items():
            transitions[i] = {
                "a": index[(p, (c + 1) % 5 if p == r else c)],
                "b": index[((p + 1) % 4, c)],
            }
        accept = [index[(p, h)] for p in range(4)]
        return d_min(dfa(transitions, index[(0, 0)], accept))

    assert set(AL) == {"a", "b"}
    bad = []
    for r in range(4):
        for h in range(5):
            witness = equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, h))
            if witness is not None:
                bad.append((r, h, witness))
    report(
        "WATOM-45-01",
        not bad,
        "all 20 atoms proved equal to their 20-state staged-count DFAs by "
        "complete product reachability, no sampling"
        if not bad
        else f"{len(bad)} atoms disagree, e.g. {bad[0]}",
    )

    # Negative control: compare each atom with the target for the WRONG residue.
    missed = [
        (r, h)
        for r in range(4)
        for h in range(5)
        if equivalence_counterexample(compile_dfa(W[r][h]), staged_target(r, (h + 1) % 5))
        is None
    ]
    report(
        "WATOM-45-01 [negative control]",
        not missed,
        "every atom is rejected against the shifted residue h+1"
        if not missed
        else f"SHIFTED RESIDUE ACCEPTED for {missed} — the checker is not discriminating",
    )


# ==========================================================================
# LAAB-04-01 and THOMAS-D2-02: arithmetic reductions, decided
# ==========================================================================
#
# Both rows have proved atoms and a *sampled composite*. The composite in each
# case is an integer identity holding for every word, and an integer identity
# whose per-letter increments are bounded is decided by a BFS: explore the
# states on which it holds, and report the first transition that breaks it.


def decide_word_identity(
    name: str, letters, start, step, ok, detail: str, *, negative: bool = False
) -> bool:
    """BFS every reachable state, requiring `ok` at each. Complete for all words.

    `step(state, letter) -> state`. Because the search only ever extends states
    that satisfy `ok`, the first violation found is a genuine counterexample
    word, and termination is guaranteed by the state set being finite.
    """
    def emit(held: bool, message: str) -> bool:
        if negative:
            report(
                f"{name} [negative control]",
                not held,
                f"the broken variant ({detail}) is rejected — {message}"
                if not held
                else f"BROKEN VARIANT ACCEPTED ({detail}) — the BFS is not discriminating",
            )
        else:
            report(name, held, message)
        return held

    seen = {start}
    frontier = deque([start])
    if not ok(start):
        return emit(False, "fails already on the empty word")
    while frontier:
        state = frontier.popleft()
        for letter in letters:
            nxt = step(state, letter)
            if not ok(nxt):
                return emit(False, f"violated at reachable state {nxt!r}")
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return emit(True, f"{detail}; holds at all {len(seen)} reachable states, no sampling")


def laab_machine(weight: int = 2):
    """binom(w,aab) mod 4 versus M1 + weight*M2. `weight != 2` breaks it."""
    # state = (#a mod 8, binom(#a,2) mod 4, binom(w,aab) mod 4, M1 mod 4, M2 mod 2)
    start = (0, 0, 0, 0, 0)

    def step(state, letter):
        n, c2, c3, m1, m2 = state
        if letter == "a":
            return ((n + 1) % 8, (c2 + n) % 4, c3, m1, m2)
        return (
            n,
            c2,
            (c3 + c2) % 4,
            (m1 + (1 if n % 4 in (2, 3) else 0)) % 4,
            (m2 + (1 if n % 8 in (3, 4, 5, 6) else 0)) % 2,
        )

    def ok(state):
        _n, _c2, c3, m1, m2 = state
        return c3 == (m1 + weight * m2) % 4

    return start, step, ok


def thomas_machine(tail_penalty: int = 1):
    """T' = |w|_a + 2|w|_b - 2*#tok - [tail=a] over the prefix code {b,aa,ab}.

    State is (parse state, D) with D the signed defect; `tail_penalty != 1`
    breaks the identity.
    """
    start = (0, 0)

    def step(state, letter):
        parse, d = state
        if parse == 0:
            return (1, d - 1) if letter == "a" else (0, d)
        return (0, d + 1)

    def ok(state):
        parse, d = state
        return d == (0 if parse == 0 else -tail_penalty)

    return start, step, ok


def check_arithmetic_reductions() -> None:
    print("\n=== LAAB-04-01: binom(w,aab) = M1 + 2*M2 (mod 4) ===")
    start, step, ok = laab_machine()
    decide_word_identity(
        "LAAB-04-01 composite",
        "ab",
        start,
        step,
        ok,
        "M1 = N_2^(4)+N_3^(4) mod 4, M2 = N_3^(8)+N_4^(8)+N_5^(8)+N_6^(8) mod 2",
    )
    start, step, ok = laab_machine(weight=1)
    decide_word_identity(
        "LAAB-04-01 composite", "ab", start, step, ok,
        "M2 given weight 1 instead of 2", negative=True,
    )

    print("\n=== THOMAS-D2-02: the flat token-counting identity ===")
    start, step, ok = thomas_machine()
    decide_word_identity(
        "THOMAS-D2-02 identity",
        "ab",
        start,
        step,
        ok,
        "#(b-terminated odd a-runs) = |w|_a + 2|w|_b - 2*#tok - [tail=a] "
        "over the prefix code {b, aa, ab}",
    )
    start, step, ok = thomas_machine(tail_penalty=0)
    decide_word_identity(
        "THOMAS-D2-02 identity", "ab", start, step, ok,
        "the [tail=a] term dropped", negative=True,
    )


def main() -> int:
    print("Completeness upgrades for rows demoted by the 2026-07-25 audit.")
    check_a5()
    check_a4_full()
    check_watom()
    check_arithmetic_reductions()
    print()
    if FAILURES:
        print(f"FAILED: {', '.join(FAILURES)}")
        return 1
    print("All checks decided (no sampling), and every negative control fired.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
