"""Target-language DFA builders for the height-one synthesis search.

Every builder returns a complete minimal DFA over a fixed alphabet, suitable
as the ``target`` of ``tools.height_search`` and as the ``target_dfa`` of a
``gsh-regex-certificate-v1`` certificate.

Two families are provided:

* word problems of finite permutation groups: ``L = { w : phi(w) = e }`` for a
  monoid morphism ``phi`` sending each letter to a permutation;
* scattered-subword counting languages ``L(u, k, n) = { w : binom(w, u) = k
  (mod n) }`` where ``binom(w, u)`` counts occurrences of ``u`` as a scattered
  subword of ``w``.

The registry at the bottom names the calibration targets and the current
counterexample candidates (see ``CANDIDATES.md``).  Registration here is a
statement about the *language*, never about its star height.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Callable, Mapping, Sequence

from tools.regex_cert import DFA

Permutation = tuple[int, ...]


def _compose(g: Permutation, h: Permutation) -> Permutation:
    """Composition ``g after h``: (g∘h)(i) = g[h[i]]."""

    return tuple(g[h[i]] for i in range(len(g)))


def _validate_permutation(perm: Sequence[int], degree: int, name: str) -> Permutation:
    image = tuple(perm)
    if sorted(image) != list(range(degree)):
        raise ValueError(f"{name}: {image!r} is not a permutation of 0..{degree - 1}")
    return image


def cycles_to_permutation(degree: int, cycles: Sequence[Sequence[int]]) -> Permutation:
    """Build a permutation of ``0..degree-1`` from 0-indexed disjoint cycles."""

    image = list(range(degree))
    for cycle in cycles:
        for position, point in enumerate(cycle):
            successor = cycle[(position + 1) % len(cycle)]
            if not (0 <= point < degree):
                raise ValueError(f"cycle point {point} out of range for degree {degree}")
            image[point] = successor
    return _validate_permutation(image, degree, "cycles_to_permutation")


def word_problem_dfa(images: Mapping[str, Sequence[int]]) -> DFA:
    """DFA of ``{ w : phi(w) = identity }`` for ``phi(letter) = images[letter]``.

    States are the elements of the submonoid generated by the images (a group,
    because permutations are invertible); the start and unique accepting state
    is the identity.  The result is minimized, so its state count equals the
    order of the generated group.
    """

    if not images:
        raise ValueError("word_problem_dfa requires at least one letter")
    degrees = {len(perm) for perm in images.values()}
    if len(degrees) != 1:
        raise ValueError("all permutations must have the same degree")
    degree = degrees.pop()
    alphabet = tuple(sorted(images))
    generators = {
        letter: _validate_permutation(images[letter], degree, f"images[{letter!r}]")
        for letter in alphabet
    }

    identity: Permutation = tuple(range(degree))
    queue: deque[Permutation] = deque([identity])
    seen: set[Permutation] = {identity}
    transition: dict[tuple[Permutation, str], Permutation] = {}
    while queue:
        element = queue.popleft()
        for letter in alphabet:
            nxt = _compose(element, generators[letter])
            transition[(element, letter)] = nxt
            if nxt not in seen:
                seen.add(nxt)
                queue.append(nxt)
    machine = DFA(alphabet, frozenset(seen), identity, frozenset({identity}), transition)
    machine.validate()
    return machine.minimized()


def subword_count_mod_dfa(u: str, k: int, n: int, alphabet: str = "ab") -> DFA:
    """DFA of ``L(u, k, n) = { w : binom(w, u) ≡ k (mod n) }``.

    A state stores ``binom(w, p) mod n`` for every nonempty prefix ``p`` of
    ``u``; reading letter ``x`` adds ``binom(w, p')`` to ``binom(w, p)``
    whenever ``p = p'x`` (with ``binom(w, ε) = 1``).
    """

    if not u:
        raise ValueError("u must be nonempty")
    if n <= 0:
        raise ValueError("n must be positive")
    if not set(u) <= set(alphabet):
        raise ValueError("u must use only letters of the alphabet")
    letters = tuple(alphabet)
    length = len(u)

    def step(counts: tuple[int, ...], x: str) -> tuple[int, ...]:
        return tuple(
            (counts[i] + ((counts[i - 1] if i > 0 else 1) if u[i] == x else 0)) % n
            for i in range(length)
        )

    start = (0,) * length
    queue: deque[tuple[int, ...]] = deque([start])
    seen: set[tuple[int, ...]] = {start}
    transition: dict[tuple[tuple[int, ...], str], tuple[int, ...]] = {}
    while queue:
        state = queue.popleft()
        for x in letters:
            nxt = step(state, x)
            transition[(state, x)] = nxt
            if nxt not in seen:
                seen.add(nxt)
                queue.append(nxt)
    accept = frozenset(state for state in seen if state[-1] == k % n)
    machine = DFA(letters, frozenset(seen), start, accept, transition)
    machine.validate()
    return machine.minimized()


def scattered_subword_count(w: str, u: str) -> int:
    """Reference implementation of ``binom(w, u)`` for tests (exact, no mod)."""

    counts = [1] + [0] * len(u)
    for x in w:
        for i in range(len(u), 0, -1):
            if u[i - 1] == x:
                counts[i] += counts[i - 1]
    return counts[len(u)]


def _ends_with_a() -> DFA:
    transition = {
        ("no", "a"): "yes",
        ("no", "b"): "no",
        ("yes", "a"): "yes",
        ("yes", "b"): "no",
    }
    machine = DFA(("a", "b"), frozenset({"no", "yes"}), "no", frozenset({"yes"}), transition)
    return machine.minimized()


def _even_a() -> DFA:
    return word_problem_dfa({"a": (1, 0), "b": (0, 1)})


def _aa_star() -> DFA:
    transition = {
        ("even", "a"): "odd",
        ("odd", "a"): "even",
        ("even", "b"): "dead",
        ("odd", "b"): "dead",
        ("dead", "a"): "dead",
        ("dead", "b"): "dead",
    }
    machine = DFA(
        ("a", "b"),
        frozenset({"even", "odd", "dead"}),
        "even",
        frozenset({"even"}),
        transition,
    )
    return machine.minimized()


@dataclass(frozen=True)
class Target:
    name: str
    description: str
    build: Callable[[], DFA]


TARGETS: dict[str, Target] = {
    target.name: target
    for target in [
        Target("ends_a", "words ending in a (star-free calibration target)", _ends_with_a),
        Target("even_a", "even number of a (height-1 calibration target)", _even_a),
        Target("aa_star", "(aa)* as a language (height-1 calibration target)", _aa_star),
        Target(
            "z3",
            "|w|_a ≡ 0 mod 3 (cyclic word problem, known height ≤ 1)",
            lambda: word_problem_dfa({"a": (1, 2, 0), "b": (0, 1, 2)}),
        ),
        Target(
            "a4_std",
            "A4 word problem, a=(123), b=(12)(34); resolved height 1 in RESULTS.md",
            lambda: word_problem_dfa(
                {
                    "a": cycles_to_permutation(4, [(0, 1, 2)]),
                    "b": cycles_to_permutation(4, [(0, 1), (2, 3)]),
                }
            ),
        ),
        Target(
            "a4_two_3cycles",
            "A4 word problem, a=(123), b=(124); no letter lands in V4 (candidate)",
            lambda: word_problem_dfa(
                {
                    "a": cycles_to_permutation(4, [(0, 1, 2)]),
                    "b": cycles_to_permutation(4, [(0, 1, 3)]),
                }
            ),
        ),
        Target(
            "s4",
            "S4 word problem, a=(1234), b=(12); abelianization tower breaks (candidate)",
            lambda: word_problem_dfa(
                {
                    "a": cycles_to_permutation(4, [(0, 1, 2, 3)]),
                    "b": cycles_to_permutation(4, [(0, 1)]),
                }
            ),
        ),
        Target(
            "a5",
            "A5 word problem, a=(12345), b=(123); simple non-solvable (main candidate)",
            lambda: word_problem_dfa(
                {
                    "a": cycles_to_permutation(5, [(0, 1, 2, 3, 4)]),
                    "b": cycles_to_permutation(5, [(0, 1, 2)]),
                }
            ),
        ),
        Target(
            "L_aab_0_4",
            "binom(w, aab) ≡ 0 mod 4; resolved height 1 in RESULTS.md",
            lambda: subword_count_mod_dfa("aab", 0, 4),
        ),
        Target(
            "L_aab_0_8",
            "binom(w, aab) ≡ 0 mod 8; next carry depth beyond the resolved n=4 (candidate)",
            lambda: subword_count_mod_dfa("aab", 0, 8),
        ),
        Target(
            "L_aabb_0_2",
            "binom(w, aabb) ≡ 0 mod 2; |u|=4 leaves the PST |u|≤3 zone (candidate)",
            lambda: subword_count_mod_dfa("aabb", 0, 2),
        ),
        Target(
            "L_abab_0_2",
            "binom(w, abab) ≡ 0 mod 2; |u|=4 alternating pattern (candidate)",
            lambda: subword_count_mod_dfa("abab", 0, 2),
        ),
    ]
}


def build_target(name: str) -> DFA:
    if name not in TARGETS:
        known = ", ".join(sorted(TARGETS))
        raise KeyError(f"unknown target {name!r}; known targets: {known}")
    return TARGETS[name].build()
