"""Anchor the L2 ground truth to Pin-Straubing-Therien 1992 section 8 itself.

`WEIS-L2-GSH-01` takes its ground truth from the regular expression as printed
in Weis 2011 p.115.  Weis attributes the language to "[30]" = PST 1992, and the
repository has so far had only that attribution: every evaluation path
(`compile_dfa`, the recursive matcher, Python `re`) starts from the same printed
string, so a transcription error in that one string would be invisible to all
three.

The primary source removes that single point of failure.  PST 1992 section 8
("Further results", p.29 of the preprint at irif.fr/~jep/PDF/StarHeight.pdf)
prints the candidate and then gives its own, independent description:

    "Unfortunately, it is even not known whether there exist languages of
     star-height greater than or equal to 2!  A possible candidate is
        L = (ab*a  u  ba*b(ab*a)*ba*b)*.
     Notice that if A is the automaton represented on Figure 6, then
        L = {u in A* | 0.u = 0 and |p(u)|_(0,b) = 0 mod 2}."

Figure 6 is a drawing and does not survive text extraction from the PDF, so its
transition table is RECONSTRUCTED here from the two constraints that fix it: the
states are {0, 1, 2}, and PST's characterization must denote the printed
language.  The reconstruction is

    a : 0 <-> 1, 2 fixed        b : 0 <-> 2, 1 fixed

i.e. the transition monoid of A is S_3, generated by the two transpositions.
Under it, `a b* a` runs 0 ->1 ->1* ->0 and uses the arrow (0,b) zero times,
while `b a* b` runs 0 ->2 ->2* ->0 and uses it once; so every generator of the
printed star returns to 0 with an even (0,b) count, which is what PST assert.

Checks (standard library only, exact, no sampling beyond the stated word bound):

  [1] The printed regex and PST's characterization agree on ALL words of length
      <= 16 (131,071 words), evaluated by two unrelated procedures: Python's `re`
      on the printed string, and a 3-state walk carrying an arrow counter.
  [2] The reconstruction is decided, not assumed: agreement is proved for every
      word by exact product-automaton reachability between the DFA of the
      printed regex and the 6-state DFA of PST's (state, arrow parity) pair.
  [3] PST's automaton, paired with the arrow parity, IS the 6-state minimal DFA
      that `weis_l2_full_gsh1.py` derives -- so the two descriptions are the
      same automaton, reached from opposite ends.
  [4] Controls.  Four perturbations of the reconstructed table and the deletion
      of the arrow-parity clause must each break agreement.

  NOT a control, recorded because it was tried and did not fire: swapping the
  roles of a and b.  That map is the state relabelling 1 <-> 2 and denotes the
  same language, so it tests nothing.  A perturbation has to change the
  language, not the names.

What this does and does not establish.  It establishes that the string this
repository compiles is the language PST described, so `WEIS-L2-GSH-01` is about
their candidate and not about a mistranscription of it.  It says nothing about
the height-one construction, which is `weis_l2_full_gsh1.py`.

Run: python3 scripts/research/weis_l2_pst_crosscheck.py
"""

from __future__ import annotations

import re
import sys
from itertools import product
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.verdict import Control, Run, exhaustive  # noqa: E402

#: The expression exactly as printed in PST 1992 section 8 and Weis 2011 p.115.
PRINTED = r"(ab*a|ba*b(ab*a)*ba*b)*"
PRINTED_RE = re.compile(f"^(?:{PRINTED})$")

#: Reconstructed Figure 6: a = (0 1), b = (0 2) on {0, 1, 2}.
FIG6 = {0: {"a": 1, "b": 2}, 1: {"a": 0, "b": 1}, 2: {"a": 2, "b": 0}}

WORD_BOUND = 16


def pst_membership(word: str, table: dict[int, dict[str, int]] = FIG6, *, parity: bool = True) -> bool:
    """PST's own condition: 0.u = 0, and the arrow (0, b) is used an even number of times."""
    state, arrows = 0, 0
    for letter in word:
        if state == 0 and letter == "b":
            arrows += 1
        state = table[state][letter]
    return state == 0 and (arrows % 2 == 0 or not parity)


def words(limit: int):
    yield ""
    for length in range(1, limit + 1):
        for letters in product("ab", repeat=length):
            yield "".join(letters)


def pst_dfa(table: dict[int, dict[str, int]] = FIG6) -> tuple[dict, int, set]:
    """PST's automaton paired with the (0,b) arrow parity: six states."""
    delta = {}
    for state in table:
        for parity in (0, 1):
            for letter in "ab":
                bumped = (parity + 1) % 2 if (state == 0 and letter == "b") else parity
                delta[((state, parity), letter)] = (table[state][letter], bumped)
    return delta, (0, 0), {(0, 0)}


def printed_dfa() -> tuple[dict, int, set]:
    """Minimal DFA of the printed regex, via `re` over a reachable-state search.

    Built by Brzozowski-style exploration using `re` as the membership oracle on
    residuals, which keeps this file independent of the repository's own
    compiler (`compile_dfa` in `weis_l2_full_gsh1.py`); the point of the file is
    to avoid sharing machinery with the thing it checks.
    """
    residual_re = {}

    def accepts(prefix: str, suffix: str) -> bool:
        return bool(PRINTED_RE.match(prefix + suffix))

    #: A residual is identified by its behaviour on all suffixes up to this
    #: length. 8 separates the 6 classes with room to spare; the assertion below
    #: fails loudly if it ever stops separating.
    probe = [w for w in words(8)]

    def signature(prefix: str) -> tuple[bool, ...]:
        return tuple(accepts(prefix, s) for s in probe)

    start = signature("")
    states = {start: ""}
    delta = {}
    frontier = [start]
    while frontier:
        nxt = []
        for sig in frontier:
            prefix = states[sig]
            for letter in "ab":
                target = signature(prefix + letter)
                if target not in states:
                    states[target] = prefix + letter
                    nxt.append(target)
                delta[(sig, letter)] = target
        frontier = nxt
    accepting = {sig for sig in states if accepts(states[sig], "")}
    return delta, start, accepting


def equivalent(left: tuple[dict, object, set], right: tuple[dict, object, set]) -> str | None:
    """Exact product reachability. Returns a separating word, or None if equal."""
    ldelta, lstart, lacc = left
    rdelta, rstart, racc = right
    seen = {(lstart, rstart)}
    frontier = [((lstart, rstart), "")]
    while frontier:
        nxt = []
        for (lstate, rstate), witness in frontier:
            if (lstate in lacc) != (rstate in racc):
                return witness
            for letter in "ab":
                pair = (ldelta[(lstate, letter)], rdelta[(rstate, letter)])
                if pair not in seen:
                    seen.add(pair)
                    nxt.append((pair, witness + letter))
        frontier = nxt
    return None


#: Perturbations of the reconstructed Figure 6. Each must break agreement with
#: the printed expression, in the vocabulary of the figure itself (an arrow
#: moved), not in the vocabulary of this program.
CONTROLS = {
    "the b-arrow out of 0 is a loop, not 0 <-> 2": (
        {0: {"a": 1, "b": 0}, 1: {"a": 0, "b": 1}, 2: {"a": 2, "b": 0}}, True),
    "b is the 3-cycle (0 2 1), not the transposition (0 2)": (
        {0: {"a": 1, "b": 2}, 1: {"a": 0, "b": 0}, 2: {"a": 2, "b": 1}}, True),
    "b loops at 2 instead of returning to 0": (
        {0: {"a": 1, "b": 2}, 1: {"a": 0, "b": 1}, 2: {"a": 2, "b": 2}}, True),
    "a loops at 1 instead of returning to 0": (
        {0: {"a": 1, "b": 2}, 1: {"a": 1, "b": 1}, 2: {"a": 2, "b": 0}}, True),
    "the (0,b) arrow-parity clause is deleted": (FIG6, False),
}


def main() -> int:
    run = Run(script="scripts/research/weis_l2_pst_crosscheck.py")

    # Controls first, so the verdict carries them: each perturbation of Figure 6
    # must produce a word on which PST's condition and the printed expression
    # disagree.
    controls = []
    for name, (table, parity) in CONTROLS.items():
        bad = next((w for w in words(12) if bool(PRINTED_RE.match(w)) != pst_membership(w, table, parity=parity)), None)
        controls.append(Control(name=name, mutation=name, rejected=bad is not None))
        if bad is not None:
            print(f"  [control fired] {name}: first disagreement {bad!r}")

    # The claim: the printed expression and PST's characterization denote the
    # same language. Decided by product reachability over the pair automaton --
    # every word, no bound -- rather than by the length-16 sweep, which is kept
    # only because it is evaluated by a different procedure (`re` on the string,
    # against a walk carrying a counter) and so cross-checks the two encodings.
    printed = printed_dfa()
    pst = pst_dfa()
    witness = equivalent(printed, pst)
    visited = len({s for s, _ in printed[0]}) * len({s for s, _ in pst[0]})
    disagree = [w for w in words(WORD_BOUND) if bool(PRINTED_RE.match(w)) != pst_membership(w)]

    run.add(exhaustive(
        "pst-figure-6",
        "WEIS-L2-PST-SRC-01",
        passed=witness is None and not disagree and len({s for s, _ in printed[0]}) == 6,
        universe=visited,
        detail=(
            "the expression printed in PST 1992 section 8 and PST's own condition "
            "'0.u = 0 and |p(u)|_(0,b) = 0 mod 2' on the reconstructed Figure 6 "
            f"(a = (0 1), b = (0 2), transition monoid S_3) denote the same language; "
            f"product reachability over <= {visited} pairs with no word bound"
            + (f"; separating word {witness!r}" if witness else "")
            + f"; independently, the two encodings agree on all {2 ** (WORD_BOUND + 1) - 1} "
            f"words of length <= {WORD_BOUND}"
        ),
        controls=controls,
        covers="claim",
        rationale=(
            "The row claims exactly one thing: that the string this repository "
            "compiles denotes the language PST described. Both descriptions are "
            "turned into DFAs and proved equal by complete product reachability, "
            "which is the whole of that statement. Figure 6's transition table is "
            "reconstructed rather than read, and the reconstruction is what the "
            "controls constrain: four perturbations of its arrows and the deletion "
            "of the arrow-parity clause each have to produce a disagreeing word, so "
            "a table that merely happened to type-check could not pass. The row does "
            "NOT cover the height-one construction, which is weis_l2_full_gsh1.py."
        ),
    ))
    return run.finish()


if __name__ == "__main__":
    sys.exit(main())
